
"""
    Royal Mail Collection Order Handler V1 (REST)

    Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

    The version of the OpenAPI document: 1.0.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictStr
from typing import List, Optional
from ..models.contract_subscription_def import ContractSubscriptionDef

class ContractCodeDef(BaseModel):
    """
    Contract details
    """
    contract_code: Optional[StrictStr] = Field(default=None, description='Contract code', alias='contractCode')
    subscription: Optional[List[ContractSubscriptionDef]] = None
