
"""
    Royal Mail Collection Order Handler V1 (REST)

    Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

    The version of the OpenAPI document: 1.0.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from pydantic import BaseModel, Field
from typing import Optional
from ..models.task_slots_def import TaskSlotsDef

class GetAvailableSlotsResponse(BaseModel):
    """
    GetAvailableSlotsResponse
    """
    task_slots: Optional[TaskSlotsDef] = Field(default=None, alias='taskSlots')
