
"""
    Royal Mail Collection Order Handler V1 (REST)

    Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

    The version of the OpenAPI document: 1.0.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr
from typing import Optional, Union

class SlotDetailsDef(BaseModel):
    """
    Node of the details data
    """
    dps: Optional[StrictStr] = Field(default=None, description='Delivery point suffix')
    delivery_office_id: Optional[Union[float, int]] = Field(default=None, description='Functional location id of Delivery office', alias='deliveryOfficeId')
    item_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description='count of Item.', alias='itemCount')
    token_id: Optional[StrictStr] = Field(default=None, description='Toekn Id.', alias='tokenId')
    token_id_expiry_time: Optional[StrictStr] = Field(default=None, description='Token id expiry time, within which it should be used to create task. This will be populated with the date time in ISO 8601 subset format.', alias='tokenIdExpiryTime')
