
"""
    Royal Mail Collection Order Handler V1 (REST)

    Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

    The version of the OpenAPI document: 1.0.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from datetime import date
from pydantic import BaseModel, Field
from typing import Optional
from ..models.estimated_window_def import EstimatedWindowDef

class SlotDateDef(BaseModel):
    """
    SlotDateDef
    """
    slot_date: Optional[date] = Field(default=None, description='Node of slot dates', alias='slotDate')
    estimated_window: Optional[EstimatedWindowDef] = Field(default=None, alias='estimatedWindow')
