# coding: utf-8

"""
    Royal Mail Collection Order Handler V1 (REST)

    Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

    The version of the OpenAPI document: 1.0.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from ..models.slot_date_def import SlotDateDef
from ..models.slot_details_def import SlotDetailsDef
from typing import Set
from typing_extensions import Self

class TaskSlotsDef(BaseModel):
    """
    Node of slots data
    """ # noqa: E501
    slot_details: Optional[SlotDetailsDef] = Field(default=None, alias="slotDetails")
    datewise_slots: Optional[List[SlotDateDef]] = Field(default=None, alias="datewiseSlots")
    __properties: ClassVar[List[str]] = ["slotDetails", "datewiseSlots"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskSlotsDef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of slot_details
        if self.slot_details:
            _dict['slotDetails'] = self.slot_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in datewise_slots (list)
        _items = []
        if self.datewise_slots:
            for _item_datewise_slots in self.datewise_slots:
                if _item_datewise_slots:
                    _items.append(_item_datewise_slots.to_dict())
            _dict['datewiseSlots'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskSlotsDef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "slotDetails": SlotDetailsDef.from_dict(obj["slotDetails"]) if obj.get("slotDetails") is not None else None,
            "datewiseSlots": [SlotDateDef.from_dict(_item) for _item in obj["datewiseSlots"]] if obj.get("datewiseSlots") is not None else None
        })
        return _obj


