# coding: utf-8

# flake8: noqa
"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from .address_find_request_def import AddressFindRequestDef
from .address_record_def import AddressRecordDef
from .address_summary_def import AddressSummaryDef
from .address_verify_req_respdef import AddressVerifyReqRespdef
from .address_verify_request_def import AddressVerifyRequestDef
from .address_verifydef import AddressVerifyDef
from .addresses_def import AddressesDef
