# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self

class AddressVerifyDef(BaseModel):
    """
    Summary of the matching address
    """ # noqa: E501
    address_line1: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(alias="addressLine1")
    address_line2: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, alias="addressLine2")
    address_line3: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, alias="addressLine3")
    post_town: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(alias="postTown")
    county: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, alias="County")
    postcode: Annotated[str, Field(min_length=1, strict=True, max_length=10)]
    __properties: ClassVar[List[str]] = ["addressLine1", "addressLine2", "addressLine3", "postTown", "County", "postcode"]


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddressVerifyDef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddressVerifyDef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "addressLine3": obj.get("addressLine3"),
            "postTown": obj.get("postTown"),
            "County": obj.get("County"),
            "postcode": obj.get("postcode")
        })
        return _obj


