# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self

class AddressSummaryDef(BaseModel):
    """
    Summary of the matching address
    """ # noqa: E501
    # address_id: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(default=None, description="Unique identifier for address record retrieval", alias="addressId")
    address_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Unique identifier for address record retrieval", alias="addressId")
    type: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Type of the response entity")
    address_summary1: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(default=None, description="Address Line 3", alias="addressSummary1")
    address_summary2: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(default=None, description="PostTown", alias="addressSummary2")
    highlight: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="A list of number ranges identifying the matched characters in the Text and Description")
    __properties: ClassVar[List[str]] = ["addressId", "type", "addressSummary1", "addressSummary2", "highlight"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddressSummaryDef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddressSummaryDef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addressId": obj.get("addressId"),
            "type": obj.get("type"),
            "addressSummary1": obj.get("addressSummary1"),
            "addressSummary2": obj.get("addressSummary2"),
            "highlight": obj.get("highlight")
        })
        return _obj


