# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import pprint
import re  # noqa: F401
import json
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field
from typing_extensions import Annotated, Self


class AddressRecordDef(BaseModel):
    """
    Full and detailed address record as available in the address store
    """  # noqa: E501
    address_id: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(
        default=None,
        description="Unique identifier for address record retrieval",
        alias="addressId"
    )
    domestic_id: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(
        default=None,
        description="Domestic ID",
        alias="DomesticId"
    )
    language: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(
        default=None,
        description="Language of the result",
        alias="Language"
    )
    language_alternatives: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(
        default=None,
        description="Available language alternatives",
        alias="LanguageAlternatives"
    )
    department: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Department",
        alias="Department"
    )
    company: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Company name",
        alias="Company"
    )
    sub_building: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Building name",
        alias="SubBuilding"
    )
    building_number: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(
        default=None,
        description="Building number",
        alias="BuildingNumber"
    )
    building_name: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Building name",
        alias="BuildingName"
    )
    secondary_street: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Secondary Street name",
        alias="SecondaryStreet"
    )
    street: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Street name",
        alias="Street"
    )
    block: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(
        default=None,
        description="block number",
        alias="Block"
    )
    neighbourhood: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Neighbourhood name",
        alias="Neighbourhood"
    )
    district: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(
        default=None,
        description="District name",
        alias="District"
    )
    city: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(
        default=None,
        description="City name",
        alias="City"
    )
    line1: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None,
        description="Address Line 1",
        alias="Line1"
    )
    line2: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None,
        description="Address Line 2",
        alias="Line2"
    )
    line3: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None,
        description="Address Line 3",
        alias="Line3"
    )
    line4: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None,
        description="Address Line 4",
        alias="Line4"
    )
    line5: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None,
        description="Address Line 5",
        alias="Line5"
    )
    admin_area_name: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Admin area",
        alias="AdminAreaName"
    )
    admin_area_code: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Admin area code",
        alias="AdminAreaCode"
    )
    province: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Province",
        alias="Province"
    )
    province_name: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="ProvinceName",
        alias="ProvinceName"
    )
    province_code: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Province Code",
        alias="ProvinceCode"
    )
    postal_code: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Postal Code",
        alias="PostalCode"
    )
    country_name: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Country Name",
        alias="CountryName"
    )
    country_iso2: Optional[Annotated[str, Field(max_length=2)]] = Field(
        default=None,
        description="2 digit Country Iso code",
        alias="CountryIso2"
    )
    country_iso3: Optional[Annotated[str, Field(max_length=3)]] = Field(
        default=None,
        description="3 digit Country Iso code",
        alias="CountryIso3"
    )
    country_iso_number: Optional[Annotated[str, BeforeValidator(lambda v: str(v)), Field(max_length=10)]] = Field(
        default=None,
        description="Country Iso Number",
        alias="CountryIsoNumber"
    )
    sorting_number1: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Sorting Number 1",
        alias="SortingNumber1"
    )
    sorting_number2: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Sorting Number 2",
        alias="SortingNumber2"
    )
    barcode: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Barcode with DPS",
        alias="Barcode"
    )
    po_box_number: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="PO Box Number",
        alias="POBoxNumber"
    )
    label: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None,
        description="Label",
        alias="Label"
    )
    type: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Type",
        alias="Type"
    )
    data_level: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(
        default=None,
        description="Data Level",
        alias="DataLevel"
    )
    __properties: ClassVar[List[str]] = ["addressId", "DomesticId", "Language", "LanguageAlternatives", "Department",
                                         "Company", "SubBuilding", "BuildingNumber", "BuildingName", "SecondaryStreet",
                                         "Street", "Block", "Neighbourhood", "District", "City", "Line1", "Line2",
                                         "Line3", "Line4", "Line5", "AdminAreaName", "AdminAreaCode", "Province",
                                         "ProvinceName", "ProvinceCode", "PostalCode", "CountryName", "CountryIso2",
                                         "CountryIso3", "CountryIsoNumber", "SortingNumber1", "SortingNumber2",
                                         "Barcode", "POBoxNumber", "Label", "Type", "DataLevel"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddressRecordDef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set(
            [
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddressRecordDef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "addressId": obj.get("addressId"),
                "DomesticId": obj.get("DomesticId"),
                "Language": obj.get("Language"),
                "LanguageAlternatives": obj.get("LanguageAlternatives"),
                "Department": obj.get("Department"),
                "Company": obj.get("Company"),
                "SubBuilding": obj.get("SubBuilding"),
                "BuildingNumber": obj.get("BuildingNumber"),
                "BuildingName": obj.get("BuildingName"),
                "SecondaryStreet": obj.get("SecondaryStreet"),
                "Street": obj.get("Street"),
                "Block": obj.get("Block"),
                "Neighbourhood": obj.get("Neighbourhood"),
                "District": obj.get("District"),
                "City": obj.get("City"),
                "Line1": obj.get("Line1"),
                "Line2": obj.get("Line2"),
                "Line3": obj.get("Line3"),
                "Line4": obj.get("Line4"),
                "Line5": obj.get("Line5"),
                "AdminAreaName": obj.get("AdminAreaName"),
                "AdminAreaCode": obj.get("AdminAreaCode"),
                "Province": obj.get("Province"),
                "ProvinceName": obj.get("ProvinceName"),
                "ProvinceCode": obj.get("ProvinceCode"),
                "PostalCode": obj.get("PostalCode"),
                "CountryName": obj.get("CountryName"),
                "CountryIso2": obj.get("CountryIso2"),
                "CountryIso3": obj.get("CountryIso3"),
                "CountryIsoNumber": obj.get("CountryIsoNumber"),
                "SortingNumber1": obj.get("SortingNumber1"),
                "SortingNumber2": obj.get("SortingNumber2"),
                "Barcode": obj.get("Barcode"),
                "POBoxNumber": obj.get("POBoxNumber"),
                "Label": obj.get("Label"),
                "Type": obj.get("Type"),
                "DataLevel": obj.get("DataLevel")
            }
        )
        return _obj
