
"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401

from pydantic import BaseModel, Field
from typing_extensions import Annotated


class AddressFindRequestDef(BaseModel):
    """
    Address search string
    """
    address_text: Annotated[str, Field(min_length=12, strict=True, max_length=200)] = Field(
        description='Full address search string',
        alias='addressText'
    )
