
"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from pydantic import BaseModel
from typing import List, Optional
from .address_summary_def import AddressSummaryDef

class AddressesDef(BaseModel):
    """
    AddressesDef
    """
    addresses: Optional[List[AddressSummaryDef]] = None
