"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import pprint
from dataclasses import dataclass
from json import JSONDecodeError
from typing import Any, Self

import httpx
from httpx import Response
from loguru import logger


class OpenApiException(Exception):
    """The base exception class for all OpenAPIExceptions"""


class ApiTypeError(OpenApiException, TypeError):
    def __init__(self, msg, path_to_item=None, valid_classes=None, key_type=None) -> None:
        """Raises an exception for TypeErrors

        Args:
            msg (str): the exception message

        Keyword Args:
            path_to_item (list): a list of keys an indices to get to the
                                 current_item
                                 None if unset
            valid_classes (tuple): the primitive classes that current item
                                   should be an instance of
                                   None if unset
            key_type (bool): False if our value is a value in a dict
                             True if it is a key in a dict
                             False if our item is an item in a list
                             None if unset
        """
        self.path_to_item = path_to_item
        self.valid_classes = valid_classes
        self.key_type = key_type
        full_msg = msg
        if path_to_item:
            full_msg = f'{msg} at {render_path(path_to_item)}'
        super().__init__(full_msg)


class ApiValueError(OpenApiException, ValueError):
    def __init__(self, msg, path_to_item=None) -> None:
        """
        Args:
            msg (str): the exception message

        Keyword Args:
            path_to_item (list) the path to the exception in the
                received_data dict. None if unset
        """

        self.path_to_item = path_to_item
        full_msg = msg
        if path_to_item:
            full_msg = f'{msg} at {render_path(path_to_item)}'
        super().__init__(full_msg)


class ApiAttributeError(OpenApiException, AttributeError):
    def __init__(self, msg, path_to_item=None) -> None:
        """
        Raised when an attribute reference or assignment fails.

        Args:
            msg (str): the exception message

        Keyword Args:
            path_to_item (None/list) the path to the exception in the
                received_data dict
        """
        self.path_to_item = path_to_item
        full_msg = msg
        if path_to_item:
            full_msg = f'{msg} at {render_path(path_to_item)}'
        super().__init__(full_msg)


class ApiKeyError(OpenApiException, KeyError):
    def __init__(self, msg, path_to_item=None) -> None:
        """
        Args:
            msg (str): the exception message

        Keyword Args:
            path_to_item (None/list) the path to the exception in the
                received_data dict
        """
        self.path_to_item = path_to_item
        full_msg = msg
        if path_to_item:
            full_msg = f'{msg} at {render_path(path_to_item)}'
        super().__init__(full_msg)


class ApiException(OpenApiException):
    def __init__(
        self,
        status=None,
        reason=None,
        http_resp=None,
        *,
        body: str | None = None,
        data: Any | None = None,
    ) -> None:
        self.status = status
        self.reason = reason
        self.body = body
        self.data = data
        self.headers = None

        if http_resp:
            if self.status is None:
                self.status = http_resp.status
            if self.reason is None:
                self.reason = http_resp.reason
            if self.body is None:
                try:
                    self.body = http_resp.data.decode('utf-8')
                except Exception:
                    pass
            self.headers = http_resp.getheaders()

    @classmethod
    def from_response(
        cls,
        *,
        http_resp,
        body: str | None,
        data: Any | None,
    ) -> Self:
        if http_resp.status == 400:
            raise BadRequestException(http_resp=http_resp, body=body, data=data)

        if http_resp.status == 401:
            raise UnauthorizedException(http_resp=http_resp, body=body, data=data)

        if http_resp.status == 403:
            raise ForbiddenException(http_resp=http_resp, body=body, data=data)

        if http_resp.status == 404:
            raise NotFoundException(http_resp=http_resp, body=body, data=data)

        # Added new conditions for 409 and 422
        if http_resp.status == 409:
            raise ConflictException(http_resp=http_resp, body=body, data=data)

        if http_resp.status == 422:
            raise UnprocessableEntityException(http_resp=http_resp, body=body, data=data)

        if 500 <= http_resp.status <= 599:
            raise ServiceException(http_resp=http_resp, body=body, data=data)
        raise ApiException(http_resp=http_resp, body=body, data=data)

    def __str__(self):
        """Custom error messages for exception"""
        error_message = f'({self.status})\nReason: {self.reason}\n'
        if self.headers:
            error_message += f'HTTP response headers: {self.headers}\n'

        if self.data or self.body:
            error_message += f'HTTP response body: {self.data or self.body}\n'

        return error_message


class BadRequestException(ApiException):
    pass


class NotFoundException(ApiException):
    pass


class UnauthorizedException(ApiException):
    pass


class ForbiddenException(ApiException):
    pass


class ServiceException(ApiException):
    pass


class ConflictException(ApiException):
    """Exception for HTTP 409 Conflict."""

    pass


class UnprocessableEntityException(ApiException):
    """Exception for HTTP 422 Unprocessable Entity."""

    pass


def render_path(path_to_item):
    """Returns a string representation of a path"""
    result = ''
    for pth in path_to_item:
        if isinstance(pth, int):
            result += f'[{pth}]'
        else:
            result += f"['{pth}']"
    return result


@dataclass
class RMError:
    cause: str
    code: str
    description: str
    resolution: str


# class RMStatusError(httpx.HTTPStatusError):
#     http_code: int
#     http_message: str
#     more_information: str
#     errors: list[RMError]
#
#     def __init__(self, request: Request, response: Response | None = None):
#         try:
#             err_json = response.json()
#         except JSONDecodeError as e:
#             msg = f'RoyalMail Http Status error for {request.url}: Unable to decode error response JSON: {e}'
#             super().__init__(msg, request=request, response=response)
#             return
#
#         self.http_code = err_json.get('httpCode', response.status_code)
#         self.http_message = err_json.get('httpMessage', '')
#         self.more_information = err_json.get('moreInformation', '')
#         errors_json = err_json.get('errors', [])
#         self.errors = [RMError(**_) for _ in errors_json]
#
#         more_msg = f' - "{self.more_information}"' if self.more_information else ''
#         errors_msg = f' - {'\n'.join([str(_) for _ in self.errors])}' if self.errors else ''
#         msg = f'RoyalMail Http Status error for {request.url}: {self.http_code}: {self.http_message}{more_msg}{errors_msg}'
#         super().__init__(msg, request=request, response=response)


class RMStatusError2(httpx.HTTPStatusError):
    http_code: int | None = None
    http_message: str = ''
    more_information: str = ''
    errors: list[RMError] = None
    a_msg: str = ''

    def __init__(self, http_error: httpx.HTTPStatusError):
        request = http_error.request
        response = http_error.response
        try:
            err_json = response.json()
        except JSONDecodeError:
            super().__init__(str(http_error), request=request, response=response)
            self.errors = []
            return

        self.http_code = err_json.get('httpCode', response.status_code)
        self.http_message = err_json.get('httpMessage', '')
        self.more_information = err_json.get('moreInformation', '')
        self.a_msg = err_json.get('message', '')
        errors_json = err_json.get('errors', [])
        self.errors = [RMError(**_) for _ in errors_json]

        infos = [self.http_code, self.http_message, self.more_information, self.a_msg]
        infos_str = ' | '.join([str(i) for i in infos if i])
        msg = f'RoyalMail Http Status error for {request.url}: {infos_str}'
        super().__init__(msg, request=request, response=response)
        ...


def raise_for_rm_status(response: Response):
    try:
        response.raise_for_status()
    except httpx.HTTPStatusError as httpx_error:
        rm_error = RMStatusError2(http_error=httpx_error)
        # rm_error = RMStatusError(request=response.request, response=response)

        if response.request.content:
            request_content = json.loads(response.request.content.decode())
            failed_req = '\n Failed Request: ' + pprint.pformat(request_content, indent=4)
        else:
            failed_req = ''

        msg = str(rm_error) + failed_req
        logger.error(msg)
        raise rm_error from httpx_error
