[project]
name = "royal-mail-combined"
version = "0.0.7"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Paw", email = "paw@pawrequest.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pawdf>=0.1.2", # array multiple labels on a4
    "httpx>=0.28.1",
    "python-dotenv>=1.2.1",
    "pydantic>=2.12.5",
    "loguru>=0.7.3",
    "pydantic-settings>=2.13.1",
    "python-dateutil>=2.9.0.post0",
    "urllib3>=2.6.3",
    "ruff>=0.15.6",
    "prek>=0.3.6",
]
[dependency-groups]
dev = [
    "pytest>=9.0.1",
]


[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
target-version = "py313"
[tool.ruff.format]
quote-style = "single"
[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
fixable = ["ALL"]
