# coding: utf-8

"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self


class AddressDef(BaseModel):
    """
    account details definition
    """  # noqa: E501
    address_line1: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(
        default=None,
        description="Address Line 1",
        alias="addressLine1"
    )
    address_line2: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(
        default=None,
        description="Address Line 2",
        alias="addressLine2"
    )
    address_line3: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(
        default=None,
        description="Address Line 3",
        alias="addressLine3"
    )
    post_town: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(
        default=None,
        description="PostTown",
        alias="postTown"
    )
    postcode: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="PostCode")
    dps: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(
        default=None,
        description="Delivery Point Suffix",
        alias="DPS"
    )
    county: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(
        default=None,
        description="County",
        alias="County"
    )
    __properties: ClassVar[List[str]] = ["addressLine1", "addressLine2", "addressLine3", "postTown", "postcode", "DPS",
                                         "County"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)
        # return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddressDef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set(
            [
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddressDef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "addressLine1": obj.get("addressLine1"),
                "addressLine2": obj.get("addressLine2"),
                "addressLine3": obj.get("addressLine3"),
                "postTown": obj.get("postTown"),
                "postcode": obj.get("postcode"),
                "DPS": obj.get("DPS"),
                "County": obj.get("County")
            }
        )
        return _obj
