# coding: utf-8

"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from .account_details_def import AccountDetailsDef
from .address_non_mandatory_def import AddressNonMandatoryDef
from .items_post_def import ItemsPostDef
from .safe_place_details_def import SafePlaceDetailsDef
from .sender_details_post_def import SenderDetailsPostDef
from typing import Set
from typing_extensions import Self

class Collection(BaseModel):
    """
    create Order
    """ # noqa: E501
    timeslot_reservation_id: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=64)]] = Field(default=None, description="time slot reservation Id", alias="timeslotReservationId")
    sender_details: SenderDetailsPostDef = Field(alias="senderDetails")
    collection_date: date = Field(description="Date of order collection", alias="collectionDate")
    account_details: AccountDetailsDef = Field(alias="accountDetails")
    address: AddressNonMandatoryDef
    items: List[ItemsPostDef]

    safe_place_details: Optional[SafePlaceDetailsDef] = Field(default=None, alias="safePlaceDetails")
    animal_hazard_details: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Details of unrestrained pets", alias="animalHazardDetails")
    suppress_rm_notifications: Optional[StrictBool] = Field(default=None, alias="suppressRmNotifications")
    __properties: ClassVar[List[str]] = ["timeslotReservationId", "senderDetails", "accountDetails", "address", "safePlaceDetails", "animalHazardDetails", "collectionDate", "items", "suppressRmNotifications"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Collection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sender_details
        if self.sender_details:
            _dict['senderDetails'] = self.sender_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of account_details
        if self.account_details:
            _dict['accountDetails'] = self.account_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of safe_place_details
        if self.safe_place_details:
            _dict['safePlaceDetails'] = self.safe_place_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Collection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timeslotReservationId": obj.get("timeslotReservationId"),
            "senderDetails": SenderDetailsPostDef.from_dict(obj["senderDetails"]) if obj.get("senderDetails") is not None else None,
            "accountDetails": AccountDetailsDef.from_dict(obj["accountDetails"]) if obj.get("accountDetails") is not None else None,
            "address": AddressNonMandatoryDef.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "safePlaceDetails": SafePlaceDetailsDef.from_dict(obj["safePlaceDetails"]) if obj.get("safePlaceDetails") is not None else None,
            "animalHazardDetails": obj.get("animalHazardDetails"),
            "collectionDate": obj.get("collectionDate"),
            "items": [ItemsPostDef.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "suppressRmNotifications": obj.get("suppressRmNotifications")
        })
        return _obj


