# coding: utf-8

"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from .account_details_def import AccountDetailsDef
from .address_def import AddressDef
from .collection_status import CollectionStatus
from .items_def import ItemsDef
from .safe_place_details_def import SafePlaceDetailsDef
from .sender_details_def import SenderDetailsDef
from typing import Set
from typing_extensions import Self

class CollectionOrderGetResponse(BaseModel):
    """
    Response for Get collection Order
    """ # noqa: E501
    collection_order_id: Optional[StrictStr] = Field(default=None, description="Collection Order Id", alias="collectionOrderId")
    timeslot_reservation_id: Optional[StrictStr] = Field(default=None, description="time slot reservation Id", alias="timeslotReservationId")
    sender_details: Optional[SenderDetailsDef] = Field(default=None, alias="senderDetails")
    account_details: Optional[AccountDetailsDef] = Field(default=None, alias="accountDetails")
    address: Optional[AddressDef] = None
    safe_place_details: Optional[SafePlaceDetailsDef] = Field(default=None, alias="safePlaceDetails")
    animal_hazard_details: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="location animal hazard details", alias="animalHazardDetails")
    collection_status: Optional[CollectionStatus] = Field(default=None, alias="collectionStatus")
    collection_date_time: Optional[datetime] = Field(default=None, description="Date of order collection", alias="collectionDateTime")
    items: Optional[List[ItemsDef]] = None
    created_on: Optional[datetime] = Field(default=None, description="Date of order creation", alias="createdOn")
    last_modified_on: Optional[datetime] = Field(default=None, description="Date of last modified", alias="lastModifiedOn")
    suppress_rm_notifications: StrictBool = Field(alias="suppressRmNotifications")
    is_collection_window_visible: StrictBool = Field(alias="isCollectionWindowVisible")
    __properties: ClassVar[List[str]] = ["collectionOrderId", "timeslotReservationId", "senderDetails", "accountDetails", "address", "safePlaceDetails", "animalHazardDetails", "collectionStatus", "collectionDateTime", "items", "createdOn", "lastModifiedOn", "suppressRmNotifications", "isCollectionWindowVisible"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CollectionOrderGetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sender_details
        if self.sender_details:
            _dict['senderDetails'] = self.sender_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of account_details
        if self.account_details:
            _dict['accountDetails'] = self.account_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of safe_place_details
        if self.safe_place_details:
            _dict['safePlaceDetails'] = self.safe_place_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CollectionOrderGetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "collectionOrderId": obj.get("collectionOrderId"),
            "timeslotReservationId": obj.get("timeslotReservationId"),
            "senderDetails": SenderDetailsDef.from_dict(obj["senderDetails"]) if obj.get("senderDetails") is not None else None,
            "accountDetails": AccountDetailsDef.from_dict(obj["accountDetails"]) if obj.get("accountDetails") is not None else None,
            "address": AddressDef.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "safePlaceDetails": SafePlaceDetailsDef.from_dict(obj["safePlaceDetails"]) if obj.get("safePlaceDetails") is not None else None,
            "animalHazardDetails": obj.get("animalHazardDetails"),
            "collectionStatus": obj.get("collectionStatus"),
            "collectionDateTime": obj.get("collectionDateTime"),
            "items": [ItemsDef.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "createdOn": obj.get("createdOn"),
            "lastModifiedOn": obj.get("lastModifiedOn"),
            "suppressRmNotifications": obj.get("suppressRmNotifications"),
            "isCollectionWindowVisible": obj.get("isCollectionWindowVisible")
        })
        return _obj


