# coding: utf-8

"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CollectionStatus(str, Enum):
    """
    CollectionStatus
    """

    """
    allowed enum values
    """
    CREATED = 'Created'
    PENDING = 'Pending'
    COLLECTIONORDERPLACED = 'CollectionOrderPlaced'
    COLLECTED = 'Collected'
    CANCELLED = 'Cancelled'
    PROCESSING = 'Processing'
    NOTCOLLECTED = 'NotCollected'
    ATTEMPTED = 'Attempted'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CollectionStatus from a JSON string"""
        return cls(json.loads(json_str))


