# coding: utf-8

"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from .collection_item_type import CollectionItemType
from .dimensions_def import DimensionsDef
from .label_info import LabelInfo
from typing import Set
from typing_extensions import Self

class ItemsDef(BaseModel):
    """
    items detail definition
    """ # noqa: E501
    item_barcode_id: Optional[Annotated[str, Field(strict=True, max_length=21)]] = Field(default=None, description="Item BarCode Id", alias="itemBarcodeId")
    item_reference: Optional[Annotated[str, Field(strict=True, max_length=40)]] = Field(default=None, alias="itemReference")
    weight_in_grams: StrictInt = Field(description="Weight of a parcel in grams", alias="weightInGrams")
    item_service_name: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Item Service Name", alias="itemServiceName")
    item_status: Optional[StrictStr] = Field(default=None, alias="itemStatus")
    dimensions: DimensionsDef
    item_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="itemPrice")
    item_type: Optional[CollectionItemType] = Field(default=None, alias="itemType")
    item_product_code: Optional[Annotated[str, Field(strict=True, max_length=5)]] = Field(default=None, alias="itemProductCode")
    label_info: Optional[LabelInfo] = Field(default=None, alias="labelInfo")
    __properties: ClassVar[List[str]] = ["itemBarcodeId", "itemReference", "weightInGrams", "itemServiceName", "itemStatus", "dimensions", "itemPrice", "itemType", "itemProductCode", "labelInfo"]

    @field_validator('item_status')
    def item_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['AwaitingCollection', 'Collected', 'NotCollected', 'Attempted']):
            raise ValueError("must be one of enum values ('AwaitingCollection', 'Collected', 'NotCollected', 'Attempted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ItemsDef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dimensions
        if self.dimensions:
            _dict['dimensions'] = self.dimensions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_info
        if self.label_info:
            _dict['labelInfo'] = self.label_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ItemsDef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "itemBarcodeId": obj.get("itemBarcodeId"),
            "itemReference": obj.get("itemReference"),
            "weightInGrams": obj.get("weightInGrams"),
            "itemServiceName": obj.get("itemServiceName"),
            "itemStatus": obj.get("itemStatus"),
            "dimensions": DimensionsDef.from_dict(obj["dimensions"]) if obj.get("dimensions") is not None else None,
            "itemPrice": obj.get("itemPrice"),
            "itemType": obj.get("itemType"),
            "itemProductCode": obj.get("itemProductCode"),
            "labelInfo": LabelInfo.from_dict(obj["labelInfo"]) if obj.get("labelInfo") is not None else None
        })
        return _obj


