"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import List, Optional, Union
from typing_extensions import Annotated
from .label_order_item import LabelOrderItem

from royal_mail_combined import RMBaseModel


class LabelCustomsInfo(RMBaseModel):
    """
    LabelCustomsInfo
    """

    currency_code: Optional[Annotated[str, Field(strict=True, max_length=3)]] = Field(
        default=None, alias='currencyCode'
    )
    total_cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias='totalCost')
    shipment_subtotal: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias='shipmentSubtotal')
    shipping_cost_charged: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias='shippingCostCharged')
    customs_duty_cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias='customsDutyCost')
    ioss_number: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias='IOSSNumber')
    air_number: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias='AIRNumber')
    customs_declaration_category: Optional[StrictStr] = Field(default=None, alias='customsDeclarationCategory')
    contents: Optional[List[LabelOrderItem]] = None

    @field_validator('customs_declaration_category')
    def customs_declaration_category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            ['none', 'gift', 'commercialSample', 'documents', 'other', 'returnedGoods', 'saleOfGoods', 'mixedContent']
        ):
            raise ValueError(
                "must be one of enum values ('none', 'gift', 'commercialSample', 'documents', 'other', 'returnedGoods', 'saleOfGoods', 'mixedContent')"
            )
        return value
