# coding: utf-8

"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from .label_address import LabelAddress
from .label_customs_info import LabelCustomsInfo
from typing import Set
from typing_extensions import Self

class LabelInfo(BaseModel):
    """
    LabelInfo
    """ # noqa: E501
    var_1_d_tracking_number: Optional[Annotated[str, Field(strict=True, max_length=13)]] = Field(default=None, alias="1DTrackingNumber")
    var_2_d_unique_identifier: Annotated[str, Field(min_length=1, strict=True, max_length=21)] = Field(alias="2DUniqueIdentifier")
    post_by_date: date = Field(alias="postByDate")
    rm_service: Annotated[str, Field(min_length=1, strict=True, max_length=50)] = Field(alias="RMService")
    price_paid: Union[StrictFloat, StrictInt] = Field(description="price paid for the postage", alias="pricePaid")
    reference_number: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias="referenceNumber")
    reference_text: Optional[Annotated[str, Field(strict=True, max_length=40)]] = Field(default=None, alias="referenceText")
    weight_in_grams: Annotated[int, Field(strict=True, ge=0)] = Field(alias="weightInGrams")
    item_format: StrictStr = Field(alias="itemFormat")
    recipient_address: LabelAddress = Field(alias="recipientAddress")
    sender_address: LabelAddress = Field(alias="senderAddress")
    customs_info: Optional[LabelCustomsInfo] = Field(default=None, alias="customsInfo")
    __properties: ClassVar[List[str]] = ["1DTrackingNumber", "2DUniqueIdentifier", "postByDate", "RMService", "pricePaid", "referenceNumber", "referenceText", "weightInGrams", "itemFormat", "recipientAddress", "senderAddress", "customsInfo"]

    @field_validator('item_format')
    def item_format_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Letter', 'LargeLetter', 'SmallParcel', 'MediumParcel']):
            raise ValueError("must be one of enum values ('Letter', 'LargeLetter', 'SmallParcel', 'MediumParcel')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LabelInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recipient_address
        if self.recipient_address:
            _dict['recipientAddress'] = self.recipient_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sender_address
        if self.sender_address:
            _dict['senderAddress'] = self.sender_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customs_info
        if self.customs_info:
            _dict['customsInfo'] = self.customs_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LabelInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "1DTrackingNumber": obj.get("1DTrackingNumber"),
            "2DUniqueIdentifier": obj.get("2DUniqueIdentifier"),
            "postByDate": obj.get("postByDate"),
            "RMService": obj.get("RMService"),
            "pricePaid": obj.get("pricePaid"),
            "referenceNumber": obj.get("referenceNumber"),
            "referenceText": obj.get("referenceText"),
            "weightInGrams": obj.get("weightInGrams"),
            "itemFormat": obj.get("itemFormat"),
            "recipientAddress": LabelAddress.from_dict(obj["recipientAddress"]) if obj.get("recipientAddress") is not None else None,
            "senderAddress": LabelAddress.from_dict(obj["senderAddress"]) if obj.get("senderAddress") is not None else None,
            "customsInfo": LabelCustomsInfo.from_dict(obj["customsInfo"]) if obj.get("customsInfo") is not None else None
        })
        return _obj


