# coding: utf-8

"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from .label_order_item import LabelOrderItem
from typing import Set
from typing_extensions import Self

class LabelCustomsInfo(BaseModel):
    """
    LabelCustomsInfo
    """ # noqa: E501
    currency_code: Optional[Annotated[str, Field(strict=True, max_length=3)]] = Field(default=None, alias="currencyCode")
    total_cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalCost")
    shipment_subtotal: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shipmentSubtotal")
    shipping_cost_charged: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shippingCostCharged")
    customs_duty_cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="customsDutyCost")
    ioss_number: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias="IOSSNumber")
    air_number: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias="AIRNumber")
    customs_declaration_category: Optional[StrictStr] = Field(default=None, alias="customsDeclarationCategory")
    contents: Optional[List[LabelOrderItem]] = None
    __properties: ClassVar[List[str]] = ["currencyCode", "totalCost", "shipmentSubtotal", "shippingCostCharged", "customsDutyCost", "IOSSNumber", "AIRNumber", "customsDeclarationCategory", "contents"]

    @field_validator('customs_declaration_category')
    def customs_declaration_category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'gift', 'commercialSample', 'documents', 'other', 'returnedGoods', 'saleOfGoods', 'mixedContent']):
            raise ValueError("must be one of enum values ('none', 'gift', 'commercialSample', 'documents', 'other', 'returnedGoods', 'saleOfGoods', 'mixedContent')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LabelCustomsInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in contents (list)
        _items = []
        if self.contents:
            for _item_contents in self.contents:
                if _item_contents:
                    _items.append(_item_contents.to_dict())
            _dict['contents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LabelCustomsInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currencyCode": obj.get("currencyCode"),
            "totalCost": obj.get("totalCost"),
            "shipmentSubtotal": obj.get("shipmentSubtotal"),
            "shippingCostCharged": obj.get("shippingCostCharged"),
            "customsDutyCost": obj.get("customsDutyCost"),
            "IOSSNumber": obj.get("IOSSNumber"),
            "AIRNumber": obj.get("AIRNumber"),
            "customsDeclarationCategory": obj.get("customsDeclarationCategory"),
            "contents": [LabelOrderItem.from_dict(_item) for _item in obj["contents"]] if obj.get("contents") is not None else None
        })
        return _obj


