
"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from datetime import date
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Optional, Union
from typing_extensions import Annotated
from .label_address import LabelAddress
from .label_customs_info import LabelCustomsInfo

class LabelInfo(BaseModel):
    """
    LabelInfo
    """
    var_1_d_tracking_number: Optional[Annotated[str, Field(strict=True, max_length=13)]] = Field(default=None, alias='1DTrackingNumber')
    var_2_d_unique_identifier: Annotated[str, Field(min_length=1, strict=True, max_length=21)] = Field(alias='2DUniqueIdentifier')
    post_by_date: date = Field(alias='postByDate')
    rm_service: Annotated[str, Field(min_length=1, strict=True, max_length=50)] = Field(alias='RMService')
    price_paid: Union[StrictFloat, StrictInt] = Field(description='price paid for the postage', alias='pricePaid')
    reference_number: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias='referenceNumber')
    reference_text: Optional[Annotated[str, Field(strict=True, max_length=40)]] = Field(default=None, alias='referenceText')
    weight_in_grams: Annotated[int, Field(strict=True, ge=0)] = Field(alias='weightInGrams')
    item_format: StrictStr = Field(alias='itemFormat')
    recipient_address: LabelAddress = Field(alias='recipientAddress')
    sender_address: LabelAddress = Field(alias='senderAddress')
    customs_info: Optional[LabelCustomsInfo] = Field(default=None, alias='customsInfo')

    @field_validator('item_format')
    def item_format_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Letter', 'LargeLetter', 'SmallParcel', 'MediumParcel']):
            raise ValueError("must be one of enum values ('Letter', 'LargeLetter', 'SmallParcel', 'MediumParcel')")
        return value
