
"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from pydantic import BaseModel, Field
from typing import Optional
from typing_extensions import Annotated

class SenderDetailsDef(BaseModel):
    """
    SenderDetailsDef
    """
    sender_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description='Name of sender', alias='senderName')
    sender_email: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description='Email Address of sender', alias='senderEmail')
