# coding: utf-8

"""
    Royal Mail Order V1 (REST)

    Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

    The version of the OpenAPI document: 1.0.44
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import pprint
import re  # noqa: F401
import json
from typing import Any, ClassVar, Dict, List, Optional, Set
from datetime import date

from typing_extensions import Annotated, Self
from pydantic import BaseModel, ConfigDict, Field, StrictBool

from .address_mandatory_def import AddressMandatoryDef
from .safe_place_details_def import SafePlaceDetailsDef
from .sender_details_def import SenderDetailsDef


class UpdateCollection(BaseModel):
    """
    create Order
    """  # noqa: E501
    timeslot_reservation_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(
        default=None,
        description="time slot reservation Id",
        alias="timeslotReservationId"
    )
    sender_details: Optional[SenderDetailsDef] = Field(default=None, alias="senderDetails")
    address: Optional[AddressMandatoryDef] = None
    safe_place_details: Optional[SafePlaceDetailsDef] = Field(default=None, alias="safePlaceDetails")
    animal_hazard_details: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="location animal hazard details",
        alias="animalHazardDetails"
    )
    collection_date: date = Field(description="Date of order collection", alias="collectionDate")
    suppress_rm_notifications: Optional[StrictBool] = Field(default=None, alias="suppressRmNotifications")
    __properties: ClassVar[List[str]] = ["timeslotReservationId", "senderDetails", "address", "safePlaceDetails",
                                         "animalHazardDetails", "collectionDate", "suppressRmNotifications"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateCollection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set(
            [
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sender_details
        if self.sender_details:
            _dict['senderDetails'] = self.sender_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of safe_place_details
        if self.safe_place_details:
            _dict['safePlaceDetails'] = self.safe_place_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateCollection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "timeslotReservationId": obj.get("timeslotReservationId"),
                "senderDetails": SenderDetailsDef.from_dict(obj["senderDetails"]) if obj.get(
                    "senderDetails"
                ) is not None else None,
                "address": AddressMandatoryDef.from_dict(obj["address"]) if obj.get("address") is not None else None,
                "safePlaceDetails": SafePlaceDetailsDef.from_dict(obj["safePlaceDetails"]) if obj.get(
                    "safePlaceDetails"
                ) is not None else None,
                "animalHazardDetails": obj.get("animalHazardDetails"),
                "collectionDate": obj.get("collectionDate"),
                "suppressRmNotifications": obj.get("suppressRmNotifications")
            }
        )
        return _obj
