"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from typing import Optional
from datetime import date

from typing_extensions import Annotated
from pydantic import Field, StrictBool

from .address_mandatory_def import AddressMandatoryDef
from .safe_place_details_def import SafePlaceDetailsDef
from .sender_details_def import SenderDetailsDef


from royal_mail_combined import RMBaseModel


class UpdateCollection(RMBaseModel):
    """
    create Order
    """

    timeslot_reservation_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(
        default=None, description='time slot reservation Id', alias='timeslotReservationId'
    )
    sender_details: Optional[SenderDetailsDef] = Field(default=None, alias='senderDetails')
    address: Optional[AddressMandatoryDef] = None
    safe_place_details: Optional[SafePlaceDetailsDef] = Field(default=None, alias='safePlaceDetails')
    animal_hazard_details: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None, description='location animal hazard details', alias='animalHazardDetails'
    )
    collection_date: date = Field(description='Date of order collection', alias='collectionDate')
    suppress_rm_notifications: Optional[StrictBool] = Field(default=None, alias='suppressRmNotifications')
