# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, TYPE_CHECKING
from typing import Set
from typing_extensions import Self

if TYPE_CHECKING:
    from royal_mail_combined.apis.parcels_apis.common.errors_def import ErrorsDef


class ErrorResponse(BaseModel):
    """
    ErrorResponse
    """ # noqa: E501
    http_code: StrictStr = Field(description="HTTP error code.  Please note that this will only be populated in the event of an error condition.", alias="httpCode")
    http_message: StrictStr = Field(description="HTTP error code description. Please note that this will only be populated in the event of an error condition.", alias="httpMessage")
    more_information: Optional[StrictStr] = Field(default=None, description="Information relating to the error condition.", alias="moreInformation")
    errors: Optional[List[ErrorsDef]] = None
    __properties: ClassVar[List[str]] = ["httpCode", "httpMessage", "moreInformation", "errors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ErrorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['errors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ErrorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "httpCode": obj.get("httpCode"),
            "httpMessage": obj.get("httpMessage"),
            "moreInformation": obj.get("moreInformation"),
            "errors": [ErrorsDef.from_dict(_item) for _item in obj["errors"]] if obj.get("errors") is not None else None
        })
        return _obj


