
"""
    Royal Mail Collection Order Handler V1 (REST)

    Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

    The version of the OpenAPI document: 1.0.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictStr
from typing import List, Optional
from .errors_def import ErrorsDef

class Model404NotFound(BaseModel):
    """
    Model404NotFound
    """
    http_code: StrictStr = Field(description='HTTP error code.  Please note that this will only be populated in the event of an error condition.', alias='httpCode')
    http_message: StrictStr = Field(description='HTTP error code description. Please note that this will only be populated in the event of an error condition.', alias='httpMessage')
    more_information: Optional[StrictStr] = Field(default=None, description='Information relating to the error condition.', alias='moreInformation')
    errors: Optional[List[ErrorsDef]] = None
