"""
Royal Mail Collection Order Handler V1 (REST)

Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

The version of the OpenAPI document: 1.0.17
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

from pydantic import Field, StrictFloat, StrictInt, StrictStr, validate_call
from typing_extensions import Annotated

ACCEPT = Annotated[
    StrictStr,
    Field(
        description='Content-Types that are acceptable for the response. Eg. application/json',
        default='application/json',
    ),
]

from royal_mail_combined.parcels_apis.collection_handler.models.get_available_slots_response import (
    GetAvailableSlotsResponse,
)
from royal_mail_combined.core.core_api_client import RequestSerialized
from royal_mail_combined.core import ApiResponse
from royal_mail_combined.core.consts_types import X_RMG_DATETIME
from royal_mail_combined.core.rest import RESTResponseType


class GetAvailableSlotsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client) -> None:
        self.api_client = api_client

    @validate_call
    def order_get_available_slots(
        self,
        dps: Annotated[StrictStr, Field(description='delivery point suffix details.')],
        item_count: Annotated[StrictInt, Field(description='item/items count.')],
        x_rmg_date_time: X_RMG_DATETIME,
        accept: ACCEPT,
        x_rmg_idempotency_key: Annotated[
            Optional[Annotated[str, Field(min_length=0, strict=True, max_length=256)]],
            Field(
                description='Identifier to help denote whether the request is idempotent Eg: ANON:www.w3.org:j6oAOxCWZh/CD723LGeXlf-01:34'
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetAvailableSlotsResponse:
        """Gets the available slots to book the order collection

        To get the available slots for order collection as per the customers request.

        :param dps: delivery point suffix details. (required)
        :type dps: str
        :param item_count: item/items count. (required)
        :type item_count: int
        :param x_rmg_date_time: This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT) (required)
        :type x_rmg_date_time: date
        :param accept: Content-Types that are acceptable for the response. Eg. application/json (required)
        :type accept: str
        :param x_rmg_idempotency_key: Identifier to help denote whether the request is idempotent Eg: ANON:www.w3.org:j6oAOxCWZh/CD723LGeXlf-01:34
        :type x_rmg_idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._order_get_available_slots_serialize(
            dps=dps,
            item_count=item_count,
            x_rmg_date_time=x_rmg_date_time,
            accept=accept,
            x_rmg_idempotency_key=x_rmg_idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'GetAvailableSlotsResponse',
            '400': 'Model400',
            '401': 'Model401',
            '404': 'Model404NotFound',
            '405': 'Model405',
            '500': 'Model500',
            '503': 'Model503',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def order_get_available_slots_with_http_info(
        self,
        dps: Annotated[StrictStr, Field(description='delivery point suffix details.')],
        item_count: Annotated[StrictInt, Field(description='item/items count.')],
        x_rmg_date_time: X_RMG_DATETIME,
        accept: ACCEPT,
        x_rmg_idempotency_key: Annotated[
            Optional[Annotated[str, Field(min_length=0, strict=True, max_length=256)]],
            Field(
                description='Identifier to help denote whether the request is idempotent Eg: ANON:www.w3.org:j6oAOxCWZh/CD723LGeXlf-01:34'
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetAvailableSlotsResponse]:
        """Gets the available slots to book the order collection

        To get the available slots for order collection as per the customers request.

        :param dps: delivery point suffix details. (required)
        :type dps: str
        :param item_count: item/items count. (required)
        :type item_count: int
        :param x_rmg_date_time: This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT) (required)
        :type x_rmg_date_time: date
        :param accept: Content-Types that are acceptable for the response. Eg. application/json (required)
        :type accept: str
        :param x_rmg_idempotency_key: Identifier to help denote whether the request is idempotent Eg: ANON:www.w3.org:j6oAOxCWZh/CD723LGeXlf-01:34
        :type x_rmg_idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._order_get_available_slots_serialize(
            dps=dps,
            item_count=item_count,
            x_rmg_date_time=x_rmg_date_time,
            accept=accept,
            x_rmg_idempotency_key=x_rmg_idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'GetAvailableSlotsResponse',
            '400': 'Model400',
            '401': 'Model401',
            '404': 'Model404NotFound',
            '405': 'Model405',
            '500': 'Model500',
            '503': 'Model503',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def order_get_available_slots_without_preload_content(
        self,
        dps: Annotated[StrictStr, Field(description='delivery point suffix details.')],
        item_count: Annotated[StrictInt, Field(description='item/items count.')],
        x_rmg_date_time: X_RMG_DATETIME,
        accept: ACCEPT,
        x_rmg_idempotency_key: Annotated[
            Optional[Annotated[str, Field(min_length=0, strict=True, max_length=256)]],
            Field(
                description='Identifier to help denote whether the request is idempotent Eg: ANON:www.w3.org:j6oAOxCWZh/CD723LGeXlf-01:34'
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Gets the available slots to book the order collection

        To get the available slots for order collection as per the customers request.

        :param dps: delivery point suffix details. (required)
        :type dps: str
        :param item_count: item/items count. (required)
        :type item_count: int
        :param x_rmg_date_time: This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT) (required)
        :type x_rmg_date_time: date
        :param accept: Content-Types that are acceptable for the response. Eg. application/json (required)
        :type accept: str
        :param x_rmg_idempotency_key: Identifier to help denote whether the request is idempotent Eg: ANON:www.w3.org:j6oAOxCWZh/CD723LGeXlf-01:34
        :type x_rmg_idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._order_get_available_slots_serialize(
            dps=dps,
            item_count=item_count,
            x_rmg_date_time=x_rmg_date_time,
            accept=accept,
            x_rmg_idempotency_key=x_rmg_idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'GetAvailableSlotsResponse',
            '400': 'Model400',
            '401': 'Model401',
            '404': 'Model404NotFound',
            '405': 'Model405',
            '500': 'Model500',
            '503': 'Model503',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _order_get_available_slots_serialize(
        self,
        dps,
        item_count,
        x_rmg_date_time,
        accept,
        x_rmg_idempotency_key,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if dps is not None:
            _query_params.append(('dps', dps))

        if item_count is not None:
            _query_params.append(('itemCount', item_count))

        # process the header parameters
        if x_rmg_date_time is not None:
            _header_params['X-RMG-Date-Time'] = x_rmg_date_time
        if accept is not None:
            _header_params['Accept'] = accept
        if x_rmg_idempotency_key is not None:
            _header_params['X-RMG-Idempotency-Key'] = x_rmg_idempotency_key
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # authentication setting
        _auth_settings: List[str] = ['Client-Secret', 'Client-Id', 'BearerAuth']

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/slots',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
