# coding: utf-8

# flake8: noqa
"""
Royal Mail Collection Order Handler V1 (REST)

Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

The version of the OpenAPI document: 1.0.17
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from .account_def import AccountDef
from .agreement_line_def import AgreementLineDef
from .contract_code_def import ContractCodeDef
from .contract_subscription_def import ContractSubscriptionDef
from .estimated_window_def import EstimatedWindowDef
from .get_available_slots_response import GetAvailableSlotsResponse
from .product_family import ProductFamily
from .product_family_def import ProductFamilyDef
from .product_family_response_def import ProductFamilyResponseDef
from .slot_date_def import SlotDateDef
from .slot_details_def import SlotDetailsDef
from .subscription_def import SubscriptionDef
from .task_slots_def import TaskSlotsDef
from .validate_subscription_response import ValidateSubscriptionResponse

__all__ = [
    "AccountDef",
    "AgreementLineDef",
    "ContractCodeDef",
    "ContractSubscriptionDef",
    "EstimatedWindowDef",
    "GetAvailableSlotsResponse",
    "ProductFamily",
    "ProductFamilyDef",
    "ProductFamilyResponseDef",
    "SlotDateDef",
    "SlotDetailsDef",
    "SubscriptionDef",
    "TaskSlotsDef",
    "ValidateSubscriptionResponse",
]
