"""
Royal Mail Collection Order Handler V1 (REST)

Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

The version of the OpenAPI document: 1.0.17
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictStr
from .agreement_line_def import AgreementLineDef
from .contract_code_def import ContractCodeDef
from .subscription_def import SubscriptionDef

from royal_mail_combined.core import RMBaseModel


class AccountDef(RMBaseModel):
    """
    node of account
    """

    account_number: StrictStr = Field(description='Account Number', alias='accountNumber')
    subscription: list[SubscriptionDef] | None = None
    agreement_line: AgreementLineDef = Field(alias='agreementLine')
    contract: ContractCodeDef | None = None
