"""
Royal Mail Collection Order Handler V1 (REST)

Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

The version of the OpenAPI document: 1.0.17
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field
from ..models.slot_date_def import SlotDateDef
from ..models.slot_details_def import SlotDetailsDef

from royal_mail_combined.core import RMBaseModel


class TaskSlotsDef(RMBaseModel):
    """
    Node of slots data
    """

    slot_details: SlotDetailsDef | None = Field(default=None, alias='slotDetails')
    datewise_slots: list[SlotDateDef] | None = Field(default=None, alias='datewiseSlots')
