"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictStr

from royal_mail_combined.core import RMBaseModel


class ErrorsDef(RMBaseModel):
    """
    Array containing error information.
    """

    code: StrictStr | None = Field(
        default=None, description='Code associated with the error condition'
    )
    description: StrictStr | None = Field(
        default=None, description='Description of the error condition'
    )
    cause: StrictStr | None = Field(default=None, description='Cause of the error (if known)')
    resolution: StrictStr | None = Field(
        default=None,
        description='Description of the resolution and action required to correct the error',
    )
