"""
Royal Mail Address V1 (REST)

Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

The version of the OpenAPI document: 1.0.9
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from typing import TYPE_CHECKING

from pydantic import Field, StrictStr

if TYPE_CHECKING:
    from royal_mail_combined.parcels_apis.common_models.errors_def import ErrorsDef


from royal_mail_combined.core import RMBaseModel


class ErrorResponseHttp(RMBaseModel):
    """
    ErrorResponse
    """

    http_code: StrictStr = Field(
        description='HTTP error code.  Please note that this will only be populated in the event of an error condition.',
        alias='httpCode',
    )
    http_message: StrictStr = Field(
        description='HTTP error code description. Please note that this will only be populated in the event of an error condition.',
        alias='httpMessage',
    )
    more_information: StrictStr | None = Field(
        default=None,
        description='Information relating to the error condition.',
        alias='moreInformation',
    )
    errors: list[ErrorsDef] | None = None
