"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictStr
from typing import List, Optional
from royal_mail_combined.parcels_apis.common_models.errors_def import ErrorsDef

from royal_mail_combined import RMBaseModel


class Model404(RMBaseModel):
    """
    Model404
    """

    http_code: StrictStr = Field(
        description='HTTP error code.  Please note that this will only be populated in the event of an error condition.',
        alias='httpCode',
    )
    http_message: StrictStr = Field(
        description='HTTP error code description. Please note that this will only be populated in the event of an error condition.',
        alias='httpMessage',
    )
    more_information: Optional[StrictStr] = Field(
        default=None, description='Information relating to the error condition.', alias='moreInformation'
    )
    errors: Optional[List[ErrorsDef]] = None
