"""
Royal Mail Collection Order Handler V1 (REST)

Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

The version of the OpenAPI document: 1.0.17
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictStr
from .errors_def import ErrorsDef

from royal_mail_combined.core import RMBaseModel


class Model404NotFound(RMBaseModel):
    """
    Model404NotFound
    """

    http_code: StrictStr = Field(
        description='HTTP error code.  Please note that this will only be populated in the event of an error condition.',
        alias='httpCode',
    )
    http_message: StrictStr = Field(
        description='HTTP error code description. Please note that this will only be populated in the event of an error condition.',
        alias='httpMessage',
    )
    more_information: StrictStr | None = Field(
        default=None,
        description='Information relating to the error condition.',
        alias='moreInformation',
    )
    errors: list[ErrorsDef] | None = None
