
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from typing import List, Optional

from pydantic import BaseModel, Field, StrictInt

from ..models.create_order_response import CreateOrderResponse
from ..models.failed_order_response import FailedOrderResponse


class CreateOrdersResponse(BaseModel):
    """
    CreateOrdersResponse
    """
    success_count: Optional[StrictInt] = Field(default=None, alias='successCount')
    errors_count: Optional[StrictInt] = Field(default=None, alias='errorsCount')
    created_orders: Optional[List[CreateOrderResponse]] = Field(default=None, alias='createdOrders')
    failed_orders: Optional[List[FailedOrderResponse]] = Field(default=None, alias='failedOrders')
