
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from datetime import datetime
from pydantic import BaseModel, Field, StrictInt, StrictStr
from typing import List, Optional
from ..models.create_order_label_error_response import CreateOrderLabelErrorResponse

class CreateOrderResponse(BaseModel):
    """
    CreateOrderResponse
    """
    order_identifier: StrictInt = Field(alias='orderIdentifier')
    order_reference: Optional[StrictStr] = Field(default=None, alias='orderReference')
    created_on: datetime = Field(alias='createdOn')
    order_date: Optional[datetime] = Field(default=None, alias='orderDate')
    printed_on: Optional[datetime] = Field(default=None, alias='printedOn')
    manifested_on: Optional[datetime] = Field(default=None, alias='manifestedOn')
    shipped_on: Optional[datetime] = Field(default=None, alias='shippedOn')
    tracking_number: Optional[StrictStr] = Field(default=None, alias='trackingNumber')
    label: Optional[StrictStr] = Field(default=None, description='label in format base64 string')
    label_errors: Optional[List[CreateOrderLabelErrorResponse]] = Field(default=None, alias='labelErrors')
    generated_documents: Optional[List[StrictStr]] = Field(default=None, alias='generatedDocuments')
