
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from datetime import datetime
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt
from typing import List, Optional, Union
from typing_extensions import Annotated
from ..models.billing_details_request import BillingDetailsRequest
from ..models.importer import Importer
from ..models.label_generation_request import LabelGenerationRequest
from ..models.postage_details_request import PostageDetailsRequest
from ..models.recipient_details_request import RecipientDetailsRequest
from ..models.sender_details_request import SenderDetailsRequest
from ..models.shipment_package_request import ShipmentPackageRequest
from ..models.tag_request import TagRequest


class CreateOrderRequest(BaseModel):
    """
    CreateOrderRequest
    """
    order_reference: Optional[Annotated[str, Field(strict=True, max_length=40)]] = Field(
        default=None,
        alias='orderReference'
    )
    is_recipient_a_business: Optional[StrictBool] = Field(
        default=None,
        description='Indicates if the recipient is a business or not. Mandatory for Business senders on orders shipping from Great Britain to Northern Ireland, which require additional information for B2B shipments. (Business senders are OBA accounts and OLP accounts declaring themselves as a Business sender).',
        alias='isRecipientABusiness'
    )
    recipient: RecipientDetailsRequest
    sender: Optional[SenderDetailsRequest] = None
    billing: Optional[BillingDetailsRequest] = None
    packages: Optional[List[ShipmentPackageRequest]] = None
    order_date: datetime = Field(alias='orderDate')
    planned_despatch_date: Optional[datetime] = Field(default=None, alias='plannedDespatchDate')
    special_instructions: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(
        default=None,
        alias='specialInstructions'
    )
    subtotal: Union[Annotated[float, Field(multiple_of=0.01, le=999999, strict=True, ge=0)], Annotated[
        int, Field(le=999999, strict=True, ge=0)]] = Field(
        description='The total value of all the goods in the order, excluding tax. This should not include retail shipping costs'
    )
    shipping_cost_charged: Union[Annotated[float, Field(multiple_of=0.01, le=999999, strict=True, ge=0)], Annotated[
        int, Field(le=999999, strict=True, ge=0)]] = Field(
        description='The shipping costs you charged to your customer',
        alias='shippingCostCharged'
    )
    other_costs: Optional[Union[Annotated[float, Field(multiple_of=0.01, le=999999, strict=True, ge=0)], Annotated[
        int, Field(le=999999, strict=True, ge=0)]]] = Field(default=None, alias='otherCosts')
    customs_duty_costs: Optional[Union[
        Annotated[float, Field(multiple_of=0.01, le=99999.99, strict=True, ge=0)], Annotated[
            int, Field(le=99999, strict=True, ge=0)]]] = Field(
        default=None,
        description='Customs Duty Costs is only supported in DDP (Delivery Duty Paid) services',
        alias='customsDutyCosts'
    )
    total: Union[Annotated[float, Field(multiple_of=0.01, le=999999, strict=True, ge=0)], Annotated[
        int, Field(le=999999, strict=True, ge=0)]] = Field(
        description='The sum of order subtotal, tax and retail shipping costs'
    )
    currency_code: Optional[Annotated[str, Field(strict=True, max_length=3)]] = Field(
        default=None,
        alias='currencyCode'
    )
    postage_details: Optional[PostageDetailsRequest] = Field(default=None, alias='postageDetails')
    tags: Optional[List[TagRequest]] = None
    label: Optional[LabelGenerationRequest] = None
    order_tax: Optional[Union[Annotated[float, Field(multiple_of=0.01, le=999999, strict=True, ge=0)], Annotated[
        int, Field(le=999999, strict=True, ge=0)]]] = Field(
        default=None,
        description='The total tax charged for the order',
        alias='orderTax'
    )
    contains_dangerous_goods: Optional[StrictBool] = Field(
        default=None,
        description='Indicates that the package contents contain a dangerous goods item',
        alias='containsDangerousGoods'
    )
    dangerous_goods_un_code: Optional[Annotated[str, Field(strict=True, max_length=4)]] = Field(
        default=None,
        description='UN Code of the dangerous goods',
        alias='dangerousGoodsUnCode'
    )
    dangerous_goods_description: Optional[
        Union[Annotated[float, Field(strict=True)], Annotated[int, Field(strict=True)]]] = Field(
        default=None,
        description='Description of the dangerous goods',
        alias='dangerousGoodsDescription'
    )
    dangerous_goods_quantity: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description='Quantity or volume of the dangerous goods',
        alias='dangerousGoodsQuantity'
    )
    importer: Optional[Importer] = None
