
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from typing import List, Optional

from pydantic import BaseModel, Field

from ..models.deleted_order_info import DeletedOrderInfo
from ..models.order_error_info import OrderErrorInfo


class DeleteOrdersResource(BaseModel):
    """
    DeleteOrdersResource
    """
    deleted_orders: Optional[List[DeletedOrderInfo]] = Field(default=None, alias='deletedOrders')
    errors: Optional[List[OrderErrorInfo]] = None
