"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from datetime import datetime
from typing import Optional

from pydantic import Field, StrictInt, StrictStr


from royal_mail_combined import RMBaseModel


class GetOrderInfoResource(RMBaseModel):
    """
    GetOrderInfoResource
    """

    order_identifier: StrictInt = Field(alias='orderIdentifier')
    order_reference: Optional[StrictStr] = Field(default=None, alias='orderReference')
    created_on: datetime = Field(alias='createdOn')
    order_date: Optional[datetime] = Field(default=None, alias='orderDate')
    printed_on: Optional[datetime] = Field(default=None, alias='printedOn')
    manifested_on: Optional[datetime] = Field(default=None, alias='manifestedOn')
    shipped_on: Optional[datetime] = Field(default=None, alias='shippedOn')
    tracking_number: Optional[StrictStr] = Field(default=None, alias='trackingNumber')
