"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictStr
from typing import List, Optional
from ..models.get_order_info_resource import GetOrderInfoResource

from royal_mail_combined import RMBaseModel


class GetOrdersResponse(RMBaseModel):
    """
    GetOrdersResponse
    """

    orders: Optional[List[GetOrderInfoResource]] = None
    continuation_token: Optional[StrictStr] = Field(default=None, alias='continuationToken')
