
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import re  # noqa: F401
from typing import List, Optional

from pydantic import BaseModel, Field, StrictStr

from ..models.get_order_details_resource import GetOrderDetailsResource


class GetOrdersDetailsResponse(BaseModel):
    """
    GetOrdersDetailsResponse
    """
    orders: Optional[List[GetOrderDetailsResource]] = None
    continuation_token: Optional[StrictStr] = Field(default=None, alias='continuationToken')
