
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr


class ManifestOrdersResponse(BaseModel):
    """
    ManifestOrdersResponse
    """
    manifest_number: Union[StrictFloat, StrictInt] = Field(alias='manifestNumber')
    document_pdf: Optional[StrictStr] = Field(default=None, description='manifest in format base64 string', alias='documentPdf')
