
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, StrictStr


class ManifestErrorsErrorDetailsResponse(BaseModel):
    """
    ManifestErrorsErrorDetailsResponse
    """
    code: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
