"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from datetime import datetime
from typing import Optional

from pydantic import Field, StrictBool, StrictStr
from typing_extensions import Annotated


from royal_mail_combined import RMBaseModel


class PostageDetailsRequest(RMBaseModel):
    """
    PostageDetailsRequest
    """

    send_notifications_to: Optional[StrictStr] = Field(default=None, alias='sendNotificationsTo')
    service_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, alias='serviceCode')
    carrier_name: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias='carrierName')
    service_register_code: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(
        default=None, alias='serviceRegisterCode'
    )
    consequential_loss: Optional[Annotated[int, Field(le=10000, strict=True, ge=0)]] = Field(
        default=None, alias='consequentialLoss'
    )
    receive_email_notification: Optional[StrictBool] = Field(default=None, alias='receiveEmailNotification')
    receive_sms_notification: Optional[StrictBool] = Field(default=None, alias='receiveSmsNotification')
    guaranteed_saturday_delivery: Optional[StrictBool] = Field(
        default=None, description='This field has been deprecated', alias='guaranteedSaturdayDelivery'
    )
    request_signature_upon_delivery: Optional[StrictBool] = Field(default=None, alias='requestSignatureUponDelivery')
    is_local_collect: Optional[StrictBool] = Field(default=None, alias='isLocalCollect')
    safe_place: Optional[Annotated[str, Field(strict=True, max_length=90)]] = Field(default=None, alias='safePlace')
    department: Optional[Annotated[str, Field(strict=True, max_length=150)]] = None
    air_number: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description='For B2B orders shipping from Great Britain to Northern Ireland, this field can be used to provide the Recipient UKIMs number.',
        alias='AIRNumber',
    )
    ioss_number: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias='IOSSNumber')
    requires_export_license: Optional[StrictBool] = Field(default=None, alias='requiresExportLicense')
    commercial_invoice_number: Optional[Annotated[str, Field(strict=True, max_length=35)]] = Field(
        default=None, alias='commercialInvoiceNumber'
    )
    commercial_invoice_date: Optional[datetime] = Field(default=None, alias='commercialInvoiceDate')
    recipient_eori_number: Optional[StrictStr] = Field(default=None, alias='recipientEoriNumber')
