
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field
from typing_extensions import Annotated


class SenderDetailsRequest(BaseModel):
    """
    SenderDetailsRequest
    """
    trading_name: Optional[Annotated[str, Field(strict=True, max_length=250)]] = Field(default=None, alias='tradingName')
    phone_number: Optional[Annotated[str, Field(strict=True, max_length=25)]] = Field(default=None, alias='phoneNumber')
    email_address: Optional[Annotated[str, Field(strict=True, max_length=254)]] = Field(default=None, alias='emailAddress')
