
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from pydantic import BaseModel, Field
from typing import Optional
from typing_extensions import Annotated

class TagRequest(BaseModel):
    """
    TagRequest
    """
    key: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    value: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
