
"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import re  # noqa: F401

from pydantic import BaseModel
from typing import List, Optional
from ..models.update_order_status_request import UpdateOrderStatusRequest

class UpdateOrdersStatusRequest(BaseModel):
    """
    UpdateOrdersStatusRequest
    """
    items: Optional[List[UpdateOrderStatusRequest]] = None
