from royal_mail_combined.click_and_drop_api.models import *
from royal_mail_combined.core.rm_basemodel import RMBaseModel
from royal_mail_combined.parcels_apis.address.models import *
from royal_mail_combined.parcels_apis.collection_handler.models import *
from royal_mail_combined.parcels_apis.collection_order.models import *
from royal_mail_combined.parcels_apis.common_models import *

__all__ = [
    'RMBaseModel',
    # click and drop
    'AddressRequest',
    'BillingDetailsRequest',
    'CreateOrderErrorResponse',
    'CreateOrderLabelErrorResponse',
    'CreateOrderRequest',
    'CreateOrderResponse',
    'CreateOrdersRequest',
    'CreateOrdersResponse',
    'DeleteOrdersResource',
    'DeletedOrderInfo',
    'DimensionsRequest',
    'ErrorResponseHttp',
    'FailedOrderResponse',
    'GetOrderDetailsResource',
    'GetOrderInfoResource',
    'GetOrderLineResult',
    'GetOrdersDetailsResponse',
    'GetOrdersResponse',
    'GetPostalDetailsResult',
    'GetShippingDetailsResult',
    'GetTagDetailsResult',
    'GetVersionResource',
    'Importer',
    'LabelGenerationRequest',
    'ManifestDetailsResponse',
    'ManifestErrorsErrorDetailsResponse',
    'ManifestErrorsResponse',
    'ManifestOrdersResponse',
    'OrderErrorInfo',
    'OrderErrorResponse',
    'OrderFieldResponse',
    'OrderUpdateError',
    'PostageDetailsRequest',
    'ProductItemRequest',
    'RecipientDetailsRequest',
    'SenderDetailsRequest',
    'ShipmentPackageRequest',
    'TagRequest',
    'UpdateOrderStatusRequest',
    'UpdateOrderStatusResponse',
    'UpdateOrdersStatusRequest',
    'UpdatedOrderInfo',
    'Service',
    'CustomerReference',
    'AddressReturns',
    'ReturnShipment',
    'ReturnsRequest',
    'ReturnsResponse',
    'ReturnsResponseShipment',
    'AvailableReturnService',
    'AvailableServicesResponse',
    # address
    'AddressRecordDef',
    'AddressRecordDefPermissive',
    'AddressSummaryDef',
    'AddressVerifable',
    # collection handler
    'AccountDef',
    'AgreementLineDef',
    'ContractCodeDef',
    'ContractSubscriptionDef',
    'EstimatedWindowDef',
    'GetAvailableSlotsResponse',
    'ProductFamily',
    'ProductFamilyDef',
    'ProductFamilyResponseDef',
    'SlotDateDef',
    'SlotDetailsDef',
    'SubscriptionDef',
    'TaskSlotsDef',
    'ValidateSubscriptionResponse',
    # collection order
    'AccountDetailsDef',
    'Collection',
    'CollectionItemType',
    'CollectionMandatory',
    'CollectionOrderCreateResponse',
    'CollectionOrderDeleteResponse',
    'CollectionOrderGetResponse',
    'CollectionOrderUpdateResponse',
    'CollectionStatusRequestDef',
    'DimensionsDef',
    'DimensionsPostDef',
    'DraftCollectionLabelRequest',
    'DraftCollectionLabelResult',
    'ErrorResponseHttp',
    'ItemsDef',
    'ItemsPostDef',
    'LabelCustomsInfo',
    'LabelInfo',
    'LabelOrderItem',
    'SafePlaceDetailsDef',
    'SenderDetailsDef',
    'SenderDetailsPostDef',
    'UpdateCollection',
    # common models
    'ErrorsDef',
    'ErrorResponseHttp',
    'Model400',
    'Model401',
    'Model403',
    'Model404',
    'Model404NotFound',
    'Model405',
    'Model500',
    'Model503',
]
