# coding: utf-8

# flake8: noqa
"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually (but i do).
"""  # noqa: E501

# import models into model package
from .return_models import (
    Service,
    CustomerReference,
    AddressReturns,
    Shipment,
    ReturnsRequest,
    ReturnsResponse,
    ReturnsResponseShipment,
    AvailableReturnService,
    AvailableServicesResponse,
)
from .address_request import AddressRequest
from .billing_details_request import BillingDetailsRequest
from .create_order_error_response import CreateOrderErrorResponse
from .create_order_label_error_response import CreateOrderLabelErrorResponse
from .create_order_request import CreateOrderRequest
from .create_order_response import CreateOrderResponse
from .create_orders_request import CreateOrdersRequest
from .create_orders_response import CreateOrdersResponse
from .delete_orders_resource import DeleteOrdersResource
from .deleted_order_info import DeletedOrderInfo
from .dimensions_request import DimensionsRequest
from .error_response import ErrorResponse
from .failed_order_response import FailedOrderResponse
from .get_order_details_resource import GetOrderDetailsResource
from .get_order_info_resource import GetOrderInfoResource
from .get_order_line_result import GetOrderLineResult
from .get_orders_details_response import GetOrdersDetailsResponse
from .get_orders_response import GetOrdersResponse
from .get_postal_details_result import GetPostalDetailsResult
from .get_shipping_details_result import GetShippingDetailsResult
from .get_tag_details_result import GetTagDetailsResult
from .get_version_resource import GetVersionResource
from .importer import Importer
from .label_generation_request import LabelGenerationRequest
from .manifest_details_response import ManifestDetailsResponse
from .manifest_errors_error_details_response import ManifestErrorsErrorDetailsResponse
from .manifest_errors_response import ManifestErrorsResponse
from .manifest_orders_response import ManifestOrdersResponse
from .order_error_info import OrderErrorInfo
from .order_error_response import OrderErrorResponse
from .order_field_response import OrderFieldResponse
from .order_update_error import OrderUpdateError
from .postage_details_request import PostageDetailsRequest
from .product_item_request import ProductItemRequest
from .recipient_details_request import RecipientDetailsRequest
from .sender_details_request import SenderDetailsRequest
from .shipment_package_request import ShipmentPackageRequest
from .tag_request import TagRequest
from .update_order_status_request import UpdateOrderStatusRequest
from .update_order_status_response import UpdateOrderStatusResponse
from .update_orders_status_request import UpdateOrdersStatusRequest
from .updated_order_info import UpdatedOrderInfo

__all__ = [
    "AddressRequest",
    "BillingDetailsRequest",
    "CreateOrderErrorResponse",
    "CreateOrderLabelErrorResponse",
    "CreateOrderRequest",
    "CreateOrderResponse",
    "CreateOrdersRequest",
    "CreateOrdersResponse",
    "DeleteOrdersResource",
    "DeletedOrderInfo",
    "DimensionsRequest",
    "ErrorResponse",
    "FailedOrderResponse",
    "GetOrderDetailsResource",
    "GetOrderInfoResource",
    "GetOrderLineResult",
    "GetOrdersDetailsResponse",
    "GetOrdersResponse",
    "GetPostalDetailsResult",
    "GetShippingDetailsResult",
    "GetTagDetailsResult",
    "GetVersionResource",
    "Importer",
    "LabelGenerationRequest",
    "ManifestDetailsResponse",
    "ManifestErrorsErrorDetailsResponse",
    "ManifestErrorsResponse",
    "ManifestOrdersResponse",
    "OrderErrorInfo",
    "OrderErrorResponse",
    "OrderFieldResponse",
    "OrderUpdateError",
    "PostageDetailsRequest",
    "ProductItemRequest",
    "RecipientDetailsRequest",
    "SenderDetailsRequest",
    "ShipmentPackageRequest",
    "TagRequest",
    "UpdateOrderStatusRequest",
    "UpdateOrderStatusResponse",
    "UpdateOrdersStatusRequest",
    "UpdatedOrderInfo",
    "Service",
    "CustomerReference",
    "AddressReturns",
    "Shipment",
    "ReturnsRequest",
    "ReturnsResponse",
    "ReturnsResponseShipment",
    "AvailableReturnService",
    "AvailableServicesResponse",
]
