"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field
from typing import Optional
from typing_extensions import Annotated

from royal_mail_combined.click_and_drop_api.models import AddressRequest


from royal_mail_combined import RMBaseModel


class BillingDetailsRequest(RMBaseModel):
    """
    <b>Billing</b> along with <b>billing.address</b> objects are required in specific case when 'Use shipping address for billing address' setting is set to 'false' and 'Recipient.AddressBookReference' is provided.
    """

    address: Optional[AddressRequest] = None
    phone_number: Optional[Annotated[str, Field(strict=True, max_length=25)]] = Field(default=None, alias='phoneNumber')
    email_address: Optional[Annotated[str, Field(strict=True, max_length=254)]] = Field(
        default=None, alias='emailAddress'
    )
