"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictInt, StrictStr

from royal_mail_combined.click_and_drop_api.models.order_field_response import OrderFieldResponse


from royal_mail_combined import RMBaseModel


class CreateOrderErrorResponse(RMBaseModel):
    """
    CreateOrderErrorResponse
    """

    error_code: StrictInt | None = Field(default=None, alias='errorCode')
    error_message: StrictStr | None = Field(default=None, alias='errorMessage')
    fields: list[OrderFieldResponse] | None = None
