"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictInt, StrictStr
from typing import Optional

from royal_mail_combined import RMBaseModel


class DeletedOrderInfo(RMBaseModel):
    """
    DeletedOrderInfo
    """

    order_identifier: Optional[StrictInt] = Field(default=None, alias='orderIdentifier')
    order_reference: Optional[StrictStr] = Field(default=None, alias='orderReference')
    order_info: Optional[StrictStr] = Field(default=None, alias='orderInfo')
