"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from typing import List, Optional

from pydantic import Field

from royal_mail_combined.rm_basemodel import order_idents_str
from royal_mail_combined.click_and_drop_api.models.deleted_order_info import DeletedOrderInfo
from royal_mail_combined.click_and_drop_api.models.order_error_info import OrderErrorInfo
from royal_mail_combined import RMBaseModel


class DeleteOrdersResource(RMBaseModel):
    """
    DeleteOrdersResource
    """

    deleted_orders: Optional[List[DeletedOrderInfo]] = Field(default=None, alias='deletedOrders')
    errors: Optional[List[OrderErrorInfo]] = None

    def order_idents(self) -> List[int | str]:
        return [_.order_identifier for _ in self.deleted_orders]

    def order_idents_str(self):
        return order_idents_str(self.order_idents())
