"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictInt

from royal_mail_combined.core import RMBaseModel


class DimensionsRequest(RMBaseModel):
    """
    It is not mandatory to include the dimensions field. If the dimensions field is included then the inner fields heightInMms, widthInMms and depthInMms must be specified with non-zero values.
    """

    height_in_mms: StrictInt = Field(alias='heightInMms')
    width_in_mms: StrictInt = Field(alias='widthInMms')
    depth_in_mms: StrictInt = Field(alias='depthInMms')
