"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from datetime import datetime

from pydantic import Field, StrictStr


from royal_mail_combined import RMBaseModel


class GetVersionResource(RMBaseModel):
    """
    GetVersionResource
    """

    commit: StrictStr | None = None
    build: StrictStr | None = None
    release: StrictStr | None = None
    release_date: datetime = Field(alias='releaseDate')
