"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401

from pydantic import Field, StrictInt, StrictStr

from royal_mail_combined.core import RMBaseModel


class OrderUpdateError(RMBaseModel):
    """
    OrderUpdateError
    """

    order_identifier: StrictInt | None = Field(default=None, alias='orderIdentifier')
    order_reference: StrictStr | None = Field(default=None, alias='orderReference')
    status: StrictStr | None = Field(default=None, description='Current status of the order')
    code: StrictStr | None = None
    message: StrictStr | None = None
