"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from ..models.dimensions_request import DimensionsRequest
from ..models.product_item_request import ProductItemRequest

from royal_mail_combined import RMBaseModel


class ShipmentPackageRequest(RMBaseModel):
    """
    ShipmentPackageRequest
    """

    weight_in_grams: Annotated[int, Field(le=30000, strict=True, ge=1)] = Field(alias='weightInGrams')
    package_format_identifier: StrictStr = Field(
        description="<b>If you have a ChannelShipper account, you can also pass the name of any of your custom package formats instead of the values below.</b><br> Enum: 'undefined', 'letter', 'largeLetter', 'smallParcel', 'mediumParcel', 'parcel', 'documents'",
        alias='packageFormatIdentifier',
    )
    custom_package_format_identifier: Optional[StrictStr] = Field(
        default=None,
        description="This field will be deprecated in the future. Please use 'packageFormatIdentifier' for custom package formats from ChannelShipper.",
        alias='customPackageFormatIdentifier',
    )
    dimensions: Optional[DimensionsRequest] = None
    contents: Optional[List[ProductItemRequest]] = None
