"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field
from ..models.order_update_error import OrderUpdateError
from ..models.updated_order_info import UpdatedOrderInfo

from royal_mail_combined.core import RMBaseModel


class UpdateOrderStatusResponse(RMBaseModel):
    """
    UpdateOrderStatusResponse
    """

    updated_orders: list[UpdatedOrderInfo] | None = Field(default=None, alias='updatedOrders')
    errors: list[OrderUpdateError] | None = None
