# coding: utf-8

"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import re  # noqa: F401
from datetime import date
from enum import StrEnum

from pydantic import Field, NonNegativeInt, StrictFloat, StrictInt, StrictStr, StringConstraints

OptionalStrictNumber = StrictFloat | StrictInt | None
from typing_extensions import Annotated

from royal_mail_combined import RMBaseModel


class SenderDetailsPostDef(RMBaseModel):
    """
    SenderDetailsPostDef
    """  # noqa: E501

    sender_name: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=100)]
    sender_email: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=50)]


class AccountDetailsDef(RMBaseModel):
    """
    account details definition
    """  # noqa: E501

    partner_id: Annotated[str | None, StringConstraints(strict=True, max_length=20)] = None
    retailer_account_number: Annotated[str | None, Field(strict=True, max_length=10)] = None


class AddressNonMandatoryDef(RMBaseModel):
    """
    account details definition
    """  # noqa: E501

    address_line1: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=64)]
    address_line2: Annotated[str | None, StringConstraints(strict=True, max_length=64)] = None
    address_line3: Annotated[str | None, StringConstraints(strict=True, max_length=64)] = None
    post_town: Annotated[str | None, StringConstraints(min_length=0, strict=True, max_length=64)] = None
    postcode: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=10)]
    dps: Annotated[str | None, StringConstraints(min_length=0, strict=True, max_length=10)] = None
    county: Annotated[str | None, StringConstraints(strict=True, max_length=64)] = None


class SafePlaceDetailsDef(RMBaseModel):
    """
    safe place details definition
    """  # noqa: E501

    location_text: Annotated[str | None, StringConstraints(strict=True, max_length=50)] = None
    location_code: Annotated[str | None, StringConstraints(strict=True, max_length=10)] = None


class DimensionsPostDef(RMBaseModel):
    """
    DimensionsPostDef
    """  # noqa: E501

    height: StrictFloat | StrictInt
    width: StrictFloat | StrictInt
    depth: StrictFloat | StrictInt


class CollectionItemType(StrEnum):
    STANDARD = 'Standard'
    NOLABEL = 'NoLabel'
    NOPACKAGE = 'NoPackage'


class LabelAddress(RMBaseModel):
    """
    LabelAddress
    """  # noqa: E501

    name: Annotated[str | None, StringConstraints(strict=True, max_length=50)] = None
    company_name: Annotated[str | None, StringConstraints(strict=True, max_length=50)]
    address_line1: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=64)]
    address_line2: Annotated[str | None, StringConstraints(strict=True, max_length=64)] = None
    address_line3: Annotated[str | None, Field(strict=True, max_length=64)] = None
    post_town: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=64)]
    county: Annotated[str | None, StringConstraints(strict=True, max_length=64)] = None
    postcode: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=10)]
    dps: Annotated[str | None, StringConstraints(strict=True, max_length=10)] = Field(default='9Z', alias='DPS')
    country_code: Annotated[str, StringConstraints(strict=True, max_length=3)] = 'GBR'


class LabelOrderItem(RMBaseModel):
    """
    LabelOrderItem
    """  # noqa: E501

    description: Annotated[str | None, StringConstraints(strict=True, max_length=50)] = None
    customs_code: Annotated[str | None, StringConstraints(strict=True, max_length=12)] = None
    quantity: StrictInt | None = None
    unit_value: OptionalStrictNumber = None
    unit_weight_in_grams: StrictInt | None = Field(default=None, alias='unitWeightInGrams')
    origin_country_code: Annotated[str | None, StringConstraints(strict=True, max_length=3)] = None


class LabelCustomsInfo(RMBaseModel):
    """
    LabelCustomsInfo
    """  # noqa: E501

    currency_code: Annotated[str | None, StringConstraints(strict=True, max_length=3)] = None
    total_cost: OptionalStrictNumber = None
    shipment_subtotal: OptionalStrictNumber = None
    shipping_cost_charged: OptionalStrictNumber = Field(default=None, alias='shippingCostCharged')
    customs_duty_cost: OptionalStrictNumber = None
    ioss_number: Annotated[str, StringConstraints(strict=True, max_length=20)] = Field(default=None, alias='IOSSNumber')
    air_number: Annotated[str, StringConstraints(strict=True, max_length=20)] = Field(default=None, alias='AIRNumber')
    customs_declaration_category: StrictStr | None = None
    contents: list[LabelOrderItem] = Field(default_factory=list)


class LabelInfo(RMBaseModel):
    """
    LabelInfo
    """  # noqa: E501

    var_1_d_tracking_number: Annotated[str | None, StringConstraints(strict=True, max_length=13)] = Field(
        default=None, alias='1DTrackingNumber'
    )
    var_2_d_unique_identifier: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=21)] = Field(
        alias='2DUniqueIdentifier'
    )
    post_by_date: date
    rm_service: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=50)] = Field(alias='RMService')
    price_paid: StrictFloat | StrictInt
    reference_number: Annotated[str | None, StringConstraints(strict=True, max_length=20)] = None
    reference_text: Annotated[str | None, StringConstraints(strict=True, max_length=40)]
    weight_in_grams: NonNegativeInt
    item_format: StrictStr
    recipient_address: LabelAddress = Field(alias='recipientAddress')
    sender_address: LabelAddress = Field(alias='senderAddress')
    customs_info: LabelCustomsInfo | None = None


class ItemsPostDef(RMBaseModel):
    """
    items detail definition
    """  # noqa: E501

    item_barcode_id: Annotated[str | None, StringConstraints(min_length=1, strict=True, max_length=21)] = None
    item_reference: Annotated[str | None, StringConstraints(strict=True, max_length=40)] = None
    weight_in_grams: NonNegativeInt
    item_service_name: Annotated[str, StringConstraints(min_length=1, strict=True, max_length=50)]
    item_status: StrictStr = 'AwaitingCollection'
    dimensions: DimensionsPostDef
    item_price: StrictFloat | StrictInt | None = None
    item_type: CollectionItemType | None = None
    item_product_code: Annotated[str | None, StringConstraints(strict=True, max_length=5)] = None
    label_info: LabelInfo | None = None


class Collection(RMBaseModel):
    timeslot_reservation_id: Annotated[str | None, StringConstraints(min_length=0, strict=True, max_length=64)] = Field(
        default=None, description='time slot reservation Id', alias='timeslotReservationId'
    )
    sender_details: SenderDetailsPostDef = Field(alias='senderDetails')
    account_details: AccountDetailsDef = Field(alias='accountDetails')
    address: AddressNonMandatoryDef
    collection_date: date
    items: list[ItemsPostDef]
    safe_place_details: SafePlaceDetailsDef | None = None
    animal_hazard_details: Annotated[str | None, StringConstraints(max_length=50)] = None
    suppress_rm_notifications: bool | None = None


