"""
Royal Mail Collection Order Handler V1 (REST)

Royal Mail Collection Order handler API exposes a REST service that allows Royal Mail customers to help in booking the doorstep collections. The purpose of this API is to allow Royal Mail customers to check the available slots and validate the subscription.

The version of the OpenAPI document: 1.0.17
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union
from datetime import date

from pydantic import Field, StrictFloat, StrictInt, StrictStr, validate_call
from typing_extensions import Annotated

from royal_mail_combined.apis.parcels_apis.collection_handler.models.product_family import ProductFamily
from royal_mail_combined.apis.parcels_apis.collection_handler.models.validate_subscription_response import (
    ValidateSubscriptionResponse,
)
from royal_mail_combined.core.api_client import RequestSerialized
from royal_mail_combined.core import ApiResponse
from royal_mail_combined.core.rest import RESTResponseType


class ProductFamilySubscriptionApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client) -> None:
        self.api_client = api_client

    @validate_call
    def order_validate_subscription(
        self,
        x_rmg_date_time: Annotated[
            date,
            Field(
                description='This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT)'
            ),
        ],
        accept: Annotated[
            StrictStr, Field(description='Content-Types that are acceptable for the response. Eg. application/json')
        ],
        product_family: ProductFamily,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ValidateSubscriptionResponse:
        """Validate subscription to book the order collection

        To validate the subscription as per the customers.

        :param x_rmg_date_time: This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT) (required)
        :type x_rmg_date_time: date
        :param accept: Content-Types that are acceptable for the response. Eg. application/json (required)
        :type accept: str
        :param product_family: (required)
        :type product_family: ProductFamily
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._order_validate_subscription_serialize(
            x_rmg_date_time=x_rmg_date_time,
            accept=accept,
            product_family=product_family,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ValidateSubscriptionResponse',
            '400': 'Model400',
            '401': 'Model401',
            '404': 'Model404',
            '405': 'Model405',
            '500': 'Model500',
            '503': 'Model503',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def order_validate_subscription_with_http_info(
        self,
        x_rmg_date_time: Annotated[
            date,
            Field(
                description='This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT)'
            ),
        ],
        accept: Annotated[
            StrictStr, Field(description='Content-Types that are acceptable for the response. Eg. application/json')
        ],
        product_family: ProductFamily,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ValidateSubscriptionResponse]:
        """Validate subscription to book the order collection

        To validate the subscription as per the customers.

        :param x_rmg_date_time: This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT) (required)
        :type x_rmg_date_time: date
        :param accept: Content-Types that are acceptable for the response. Eg. application/json (required)
        :type accept: str
        :param product_family: (required)
        :type product_family: ProductFamily
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._order_validate_subscription_serialize(
            x_rmg_date_time=x_rmg_date_time,
            accept=accept,
            product_family=product_family,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ValidateSubscriptionResponse',
            '400': 'Model400',
            '401': 'Model401',
            '404': 'Model404',
            '405': 'Model405',
            '500': 'Model500',
            '503': 'Model503',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def order_validate_subscription_without_preload_content(
        self,
        x_rmg_date_time: Annotated[
            date,
            Field(
                description='This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT)'
            ),
        ],
        accept: Annotated[
            StrictStr, Field(description='Content-Types that are acceptable for the response. Eg. application/json')
        ],
        product_family: ProductFamily,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Validate subscription to book the order collection

        To validate the subscription as per the customers.

        :param x_rmg_date_time: This should be populated with the date time in ISO 8601 subset format below when the message was generated. Eg. 2016-10-20T10:04:00+01:00 YYYY-MM-DDThh:mm:ss±hh:mm (To be used when there is an offset to GMT) YYYY-MM-DDThh:mm:ssZ  (To be used when value is in GMT) (required)
        :type x_rmg_date_time: date
        :param accept: Content-Types that are acceptable for the response. Eg. application/json (required)
        :type accept: str
        :param product_family: (required)
        :type product_family: ProductFamily
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._order_validate_subscription_serialize(
            x_rmg_date_time=x_rmg_date_time,
            accept=accept,
            product_family=product_family,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ValidateSubscriptionResponse',
            '400': 'Model400',
            '401': 'Model401',
            '404': 'Model404',
            '405': 'Model405',
            '500': 'Model500',
            '503': 'Model503',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _order_validate_subscription_serialize(
        self,
        x_rmg_date_time,
        accept,
        product_family,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_rmg_date_time is not None:
            _header_params['X-RMG-Date-Time'] = x_rmg_date_time
        if accept is not None:
            _header_params['Accept'] = accept
        # process the form parameters
        # process the body parameter
        if product_family is not None:
            _body_params = product_family

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = self.api_client.select_header_content_type(['application/json'])
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = ['Client-Secret', 'Client-Id', 'BearerAuth']

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/productfamily/subscription',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
