# coding: utf-8

# flake8: noqa
"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from .account_details_def import AccountDetailsDef
from ...address.models.address import AddressDefault, AddressBasic, AddressDps
from .collection import Collection
from .collection_item_type import CollectionItemType
from .collection_mandatory import CollectionMandatory
from .collection_order_create_response import CollectionOrderCreateResponse
from .collection_order_delete_response import CollectionOrderDeleteResponse
from .collection_order_get_response import CollectionOrderGetResponse
from .collection_order_update_response import CollectionOrderUpdateResponse
from .collection_status import CollectionStatus
from .collection_status_request_def import CollectionStatusRequestDef
from .dimensions_def import DimensionsDef
from .dimensions_post_def import DimensionsPostDef
from .draft_collection_label_request import DraftCollectionLabelRequest
from .draft_collection_label_result import DraftCollectionLabelResult
from .error_response import ErrorResponse
from .items_def import ItemsDef
from .items_post_def import ItemsPostDef
from .label_address import LabelAddress
from .label_customs_info import LabelCustomsInfo
from .label_info import LabelInfo
from .label_order_item import LabelOrderItem
from .safe_place_details_def import SafePlaceDetailsDef
from .sender_details_def import SenderDetailsDef
from .sender_details_post_def import SenderDetailsPostDef
from .update_collection import UpdateCollection


__all__ = [
    "AccountDetailsDef",
    "Collection",
    "CollectionItemType",
    "CollectionMandatory",
    "CollectionOrderCreateResponse",
    "CollectionOrderDeleteResponse",
    "CollectionOrderGetResponse",
    "CollectionOrderUpdateResponse",
    "CollectionStatus",
    "CollectionStatusRequestDef",
    "DimensionsDef",
    "DimensionsPostDef",
    "DraftCollectionLabelRequest",
    "DraftCollectionLabelResult",
    "ErrorResponse",
    "ItemsDef",
    "ItemsPostDef",
    "LabelAddress",
    "LabelCustomsInfo",
    "LabelInfo",
    "LabelOrderItem",
    "SafePlaceDetailsDef",
    "SenderDetailsDef",
    "SenderDetailsPostDef",
    "UpdateCollection",
]
