"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from typing import Annotated

from pydantic import Field

from royal_mail_combined.core import RMBaseModel


class AccountDetailsDef(RMBaseModel):
    partner_id: Annotated[str, Field(strict=True, max_length=20)] | None = Field(
        default=None, description='Partner Id', alias='partnerId'
    )
    retailer_account_number: Annotated[str, Field(strict=True, max_length=10)] | None = Field(
        default=None, description='Account number', alias='retailerAccountNumber'
    )
