"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field
from typing import Annotated

from royal_mail_combined import RMBaseModel


class AddressNonMandatoryDef(RMBaseModel):
    """
    account details definition
    """

    address_line1: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(
        description='Address Line 1', alias='addressLine1'
    )
    address_line2: Annotated[str, Field(strict=True, max_length=64)] | None = Field(
        default=None, description='Address Line 2', alias='addressLine2'
    )
    address_line3: Annotated[str, Field(strict=True, max_length=64)] | None = Field(
        default=None, description='Address Line 3', alias='addressLine3'
    )
    post_town: Annotated[str, Field(min_length=0, strict=True, max_length=64)] | None = Field(
        default=' ', description='PostTown', alias='postTown'
    )
    postcode: Annotated[str, Field(min_length=1, strict=True, max_length=10)] = Field(description='PostCode')
    dps: Annotated[str, Field(min_length=0, strict=True, max_length=10)] | None = Field(
        default=None, description='Delivery Point Suffix', alias='DPS'
    )
    county: Annotated[str, Field(strict=True, max_length=64)] | None = Field(
        default=None, description='County', alias='County'
    )
