"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictStr, field_validator


from royal_mail_combined.core import RMBaseModel


class CollectionStatusRequestDef(RMBaseModel):
    """
    CollectionStatusRequestDef
    """

    status: StrictStr = Field(description='status of the collection which is required')

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in {'Created', 'CollectionOrderPlaced', 'Collected', 'Cancelled', 'Attempted'}:
            raise ValueError(
                "must be one of enum values ('Created', 'CollectionOrderPlaced', 'Collected', 'Cancelled', 'Attempted')"
            )
        return value
