"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from datetime import datetime
from pydantic import Field, StrictBool, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from .account_details_def import AccountDetailsDef
from .address_def import AddressDef
from .collection_status import CollectionStatus
from .items_def import ItemsDef
from .safe_place_details_def import SafePlaceDetailsDef
from .sender_details_def import SenderDetailsDef

from royal_mail_combined import RMBaseModel


class CollectionOrderGetResponse(RMBaseModel):
    """
    Response for Get collection Order
    """

    collection_order_id: Optional[StrictStr] = Field(
        default=None, description='Collection Order Id', alias='collectionOrderId'
    )
    timeslot_reservation_id: Optional[StrictStr] = Field(
        default=None, description='time slot reservation Id', alias='timeslotReservationId'
    )
    sender_details: Optional[SenderDetailsDef] = Field(default=None, alias='senderDetails')
    account_details: Optional[AccountDetailsDef] = Field(default=None, alias='accountDetails')
    address: Optional[AddressDef] = None
    safe_place_details: Optional[SafePlaceDetailsDef] = Field(default=None, alias='safePlaceDetails')
    animal_hazard_details: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None, description='location animal hazard details', alias='animalHazardDetails'
    )
    collection_status: Optional[CollectionStatus] = Field(default=None, alias='collectionStatus')
    collection_date_time: Optional[datetime] = Field(
        default=None, description='Date of order collection', alias='collectionDateTime'
    )
    items: Optional[List[ItemsDef]] = None
    created_on: Optional[datetime] = Field(default=None, description='Date of order creation', alias='createdOn')
    last_modified_on: Optional[datetime] = Field(
        default=None, description='Date of last modified', alias='lastModifiedOn'
    )
    suppress_rm_notifications: StrictBool = Field(alias='suppressRmNotifications')
    is_collection_window_visible: StrictBool = Field(alias='isCollectionWindowVisible')
