"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from datetime import date
from pydantic import Field, StrictBool
from typing import List, Optional
from typing_extensions import Annotated
from .account_details_def import AccountDetailsDef
from .address_non_mandatory_def import AddressNonMandatoryDef
from .items_post_def import ItemsPostDef
from .safe_place_details_def import SafePlaceDetailsDef
from .sender_details_post_def import SenderDetailsPostDef

from royal_mail_combined import RMBaseModel


class Collection(RMBaseModel):
    """
    create Order
    """

    timeslot_reservation_id: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=64)]] = Field(
        default=None, description='time slot reservation Id', alias='timeslotReservationId'
    )
    sender_details: SenderDetailsPostDef = Field(alias='senderDetails')
    collection_date: date = Field(description='Date of order collection', alias='collectionDate')
    account_details: AccountDetailsDef = Field(alias='accountDetails')
    address: AddressNonMandatoryDef
    items: List[ItemsPostDef]

    safe_place_details: Optional[SafePlaceDetailsDef] = Field(default=None, alias='safePlaceDetails')
    animal_hazard_details: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None, description='Details of unrestrained pets', alias='animalHazardDetails'
    )
    suppress_rm_notifications: Optional[StrictBool] = Field(default=None, alias='suppressRmNotifications')
