"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from datetime import datetime
from typing import Annotated

from pydantic import Field, StrictBool, StrictStr

from royal_mail_combined.core import RMBaseModel
from royal_mail_combined.core.consts_types import CollectionStatus

from ...address.models.address import AddressDefault
from .account_details_def import AccountDetailsDef
from .items_def import ItemsDef
from .safe_place_details_def import SafePlaceDetailsDef
from .sender_details_def import SenderDetailsDef


class CollectionOrderGetResponse(RMBaseModel):
    """
    Response for Get collection Order
    """

    collection_order_id: StrictStr | None = Field(
        default=None, description='Collection Order Id', alias='collectionOrderId'
    )
    timeslot_reservation_id: StrictStr | None = Field(
        default=None, description='time slot reservation Id', alias='timeslotReservationId'
    )
    sender_details: SenderDetailsDef | None = Field(default=None, alias='senderDetails')
    account_details: AccountDetailsDef | None = Field(default=None, alias='accountDetails')
    address: AddressDefault | None = None
    safe_place_details: SafePlaceDetailsDef | None = Field(default=None, alias='safePlaceDetails')
    animal_hazard_details: Annotated[str, Field(strict=True, max_length=50)] | None = Field(
        default=None, description='location animal hazard details', alias='animalHazardDetails'
    )
    collection_status: CollectionStatus | None = Field(default=None, alias='collectionStatus')
    collection_date_time: datetime | None = Field(
        default=None, description='Date of order collection', alias='collectionDateTime'
    )
    items: list[ItemsDef] | None = None
    created_on: datetime | None = Field(default=None, description='Date of order creation', alias='createdOn')
    last_modified_on: datetime | None = Field(default=None, description='Date of last modified', alias='lastModifiedOn')
    suppress_rm_notifications: StrictBool = Field(alias='suppressRmNotifications')
    is_collection_window_visible: StrictBool = Field(alias='isCollectionWindowVisible')
