"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from datetime import date
from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Annotated
from .label_address import LabelAddress
from .label_customs_info import LabelCustomsInfo

from royal_mail_combined.core import RMBaseModel


class DraftCollectionLabelRequest(RMBaseModel):
    """
    DraftCollectionLabelRequest
    """

    var_1_d_tracking_number: str = Field(min_length=1, strict=True, max_length=13, alias="1DTrackingNumber")
    var_2_d_unique_identifier: str = Field(min_length=1, strict=True, max_length=21, alias="2DUniqueIdentifier")
    post_by_date: date | None = None
    rm_service: str | None = Field(default=None, alias="RMService", strict=True, max_length=50)
    price_paid: StrictFloat | StrictInt | None = Field(default=None, alias="pricePaid")
    reference_number: Annotated[str, Field(strict=True, max_length=20)] | None = None
    display_reference_as_barcode: StrictBool | None = None
    reference_text: Annotated[str, Field(strict=True, max_length=40)] | None = None
    weight_in_grams: StrictInt | None = Field(default=None, alias="weightInGrams")
    item_format: StrictStr | None = Field(default=None, alias="itemFormat")
    recipient_address: LabelAddress = Field(alias="recipientAddress")
    sender_address: LabelAddress | None = Field(default=None, alias="senderAddress")
    customs_info: LabelCustomsInfo | None = Field(default=None, alias="customsInfo")
