"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Annotated
from .collection_item_type import CollectionItemType
from .dimensions_post_def import DimensionsPostDef
from .label_info import LabelInfo

from royal_mail_combined.core import RMBaseModel


class ItemsPostDef(RMBaseModel):
    """
    items detail definition
    """

    item_barcode_id: Annotated[str, Field(min_length=1, strict=True, max_length=21)]
    weight_in_grams: Annotated[int, Field(strict=True, ge=0)]
    item_service_name: Annotated[str, Field(min_length=1, strict=True, max_length=50)]
    dimensions: DimensionsPostDef
    item_reference: Annotated[str, Field(strict=True, max_length=40)] | None = None
    item_status: StrictStr | None = Field(default=None, alias='itemStatus')
    item_price: StrictFloat | StrictInt | None = Field(
        default=None,
        description='Price paid for the doorstep collection for the item',
        alias='itemPrice',
    )
    item_type: CollectionItemType | None = None
    item_product_code: Annotated[str, Field(strict=True, max_length=5)] | None = None
    label_info: LabelInfo | None = None

    @field_validator('item_status')
    def item_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in {
            'AwaitingCollection',
            'Collected',
            'NotCollected',
            'Processing',
            'Attempted',
        }:
            raise ValueError(
                "must be one of enum values ('AwaitingCollection', 'Collected', 'NotCollected', 'Processing', 'Attempted')"
            )
        return value
