"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field, StrictFloat, StrictInt, StrictStr
from typing import Annotated
from .collection_item_type import CollectionItemType
from .dimensions_def import DimensionsDef
from .label_info import LabelInfo

from royal_mail_combined.core import RMBaseModel


class ItemsDef(RMBaseModel):
    """
    items detail definition
    """

    item_barcode_id: Annotated[str, Field(strict=True, max_length=21)] | None = Field(
        default=None, description="Item BarCode Id", alias="itemBarcodeId"
    )
    item_reference: Annotated[str, Field(strict=True, max_length=40)] | None = Field(
        default=None, alias="itemReference"
    )
    weight_in_grams: StrictInt = Field(description="Weight of a parcel in grams", alias="weightInGrams")
    item_service_name: Annotated[str, Field(strict=True, max_length=50)] | None = Field(
        default=None, description="Item Service Name", alias="itemServiceName"
    )
    item_status: StrictStr | None = Field(default=None, alias="itemStatus")
    dimensions: DimensionsDef
    item_price: StrictFloat | StrictInt | None = Field(default=None, alias="itemPrice")
    item_type: CollectionItemType | None = Field(default=None, alias="itemType")
    item_product_code: Annotated[str, Field(strict=True, max_length=5)] | None = Field(
        default=None, alias="itemProductCode"
    )
    label_info: LabelInfo | None = Field(default=None, alias="labelInfo")
