"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from typing import Annotated, Self

from pydantic import Field, StrictFloat, StrictInt

from royal_mail_combined.core import RMBaseModel
from royal_mail_combined.core.consts_types import (
    ItemStatus,
    ReturnsServiceNames,
    StrictStr5,
    StrictStr21,
    StrictStr40,
    StrictStr50,
)

from .collection_item_type import CollectionItemType
from .dimensions_post_def import DimensionsPostDef
from .label_info import LabelInfo


class ItemsPostDef(RMBaseModel):
    item_barcode_id: StrictStr21
    weight_in_grams: Annotated[int, Field(strict=True, ge=0)]
    item_service_name: StrictStr50
    dimensions: DimensionsPostDef
    item_reference: StrictStr40 | None = None
    item_status: ItemStatus | None = None
    item_price: StrictFloat | StrictInt | None = Field(
        default=None,
        description='Price paid for the doorstep collection for the item',
        alias='itemPrice',
    )
    item_type: CollectionItemType | None = None
    item_product_code: StrictStr5 | None = None
    label_info: LabelInfo | None = None

    @classmethod
    def tracked_24_return_standard(cls, barcode_id: str, box_weight_kg: int, dims: DimensionsPostDef) -> Self:
        return cls(
            item_barcode_id=barcode_id,
            weight_in_grams=1000 * box_weight_kg,
            item_service_name=ReturnsServiceNames.TRACKED_24,
            item_type=CollectionItemType.STANDARD,
            dimensions=dims,
        )
