"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from datetime import date
from typing import Annotated

from pydantic import Field, StrictFloat, StrictInt, StrictStr, field_validator

from royal_mail_combined.core import RMBaseModel
from royal_mail_combined.core.consts_types import (
    LabelPackageFormat,
    StrictStr13,
    StrictStr20,
    StrictStr21,
    StrictStr40,
    StrictStr50,
)

from ...address.models.address import LabelAddress
from .label_customs_info import LabelCustomsInfo


class LabelInfo(RMBaseModel):
    """
    LabelInfo
    """

    var_1_d_tracking_number: StrictStr13 | None = Field(alias="1DTrackingNumber")
    var_2_d_unique_identifier: StrictStr21 = Field(alias="2DUniqueIdentifier")
    post_by_date: date = Field(alias="postByDate")
    rm_service: StrictStr50 = Field(alias="RMService")
    price_paid: StrictFloat | StrictInt = Field(description="price paid for the postage", alias="pricePaid")
    reference_number: StrictStr20 | None = None
    reference_text: StrictStr40 | None = None
    weight_in_grams: Annotated[int, Field(strict=True, ge=0)]
    item_format: LabelPackageFormat
    recipient_address: LabelAddress
    sender_address: LabelAddress
    customs_info: LabelCustomsInfo | None = None

    @field_validator("item_format")
    def item_format_validate_enum(cls, value):
        """Validates the enum"""
        if value not in {"Letter", "LargeLetter", "SmallParcel", "MediumParcel"}:
            raise ValueError("must be one of enum values ('Letter', 'LargeLetter', 'SmallParcel', 'MediumParcel')")
        return value
