"""
Royal Mail Order V1 (REST)

Royal Mail Order API exposes a REST service that allows third party retailers to create, update, retrieve or cancel an order.  There are no costs to customers for using the Royal Mail Order API V1 services, however customers’ development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.

The version of the OpenAPI document: 1.0.44
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field
from typing import Annotated

from royal_mail_combined.core import RMBaseModel


class LabelAddress(RMBaseModel):
    """
    LabelAddress
    """

    name: Annotated[str, Field(strict=True, max_length=50)] | None = None
    company_name: Annotated[str, Field(strict=True, max_length=50)] | None = None
    address_line1: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    address_line2: Annotated[str, Field(strict=True, max_length=64)] | None = None
    address_line3: Annotated[str, Field(strict=True, max_length=64)] | None = None
    post_town: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    county: Annotated[str, Field(strict=True, max_length=64)] | None = None
    postcode: Annotated[str, Field(min_length=1, strict=True, max_length=10)]
    dps: Annotated[str, Field(strict=True, max_length=10)] | None = Field(default='9Z', alias='DPS')
    country_code: Annotated[str, Field(strict=True, max_length=3)] | None = 'GBR'
