"""
Royal Mail Address V1 (REST)

Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

The version of the OpenAPI document: 1.0.9
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field
from typing import Optional
from typing_extensions import Annotated

from royal_mail_combined import RMBaseModel


class AddressVerifyDef(RMBaseModel):
    """
    Summary of the matching address
    """

    address_line1: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(alias='addressLine1')
    address_line2: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(
        default=None, alias='addressLine2'
    )
    address_line3: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(
        default=None, alias='addressLine3'
    )
    post_town: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(alias='postTown')
    county: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, alias='County')
    postcode: Annotated[str, Field(min_length=1, strict=True, max_length=10)]
