"""
Royal Mail Address V1 (REST)

Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

The version of the OpenAPI document: 1.0.9
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import re  # noqa: F401
from typing import Annotated

from pydantic import Field

from royal_mail_combined.core import RMBaseModel


class AddressSummaryDef(RMBaseModel):
    """
    Summary of the matching address
    """

    # address_id: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(default=None, description="Unique identifier for address record retrieval", alias="addressId")
    address_id: Annotated[str, Field(strict=True)] | None = Field(
        default=None,
        description='Unique identifier for address record retrieval',
        alias='addressId',
    )
    type: Annotated[str, Field(strict=True, max_length=50)] | None = Field(
        default=None, description='Type of the response entity'
    )
    address_summary1: Annotated[str, Field(strict=True, max_length=200)] | None = Field(
        default=None, description='Address Line 3', alias='addressSummary1'
    )
    address_summary2: Annotated[str, Field(strict=True, max_length=200)] | None = Field(
        default=None, description='PostTown', alias='addressSummary2'
    )
    highlight: Annotated[str, Field(strict=True, max_length=50)] | None = Field(
        default=None,
        description='A list of number ranges identifying the matched characters in the Text and Description',
    )


class AddressesDef(RMBaseModel):
    """
    AddressesDef
    """

    addresses: list[AddressSummaryDef] | None = None
