"""
Royal Mail Address V1 (REST)

Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

The version of the OpenAPI document: 1.0.9
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field
from typing import List, Optional
from typing_extensions import Annotated
from .address_verifydef import AddressVerifyDef

from royal_mail_combined import RMBaseModel


class AddressVerifyRequestDef(RMBaseModel):
    """
    AddressVerifyRequestDef
    """

    addresses: Optional[Annotated[List[AddressVerifyDef], Field(min_length=1, max_length=100)]] = Field(
        default=None, alias='Addresses'
    )
