"""
Royal Mail Address V1 (REST)

Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

The version of the OpenAPI document: 1.0.9
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import re  # noqa: F401

from pydantic import Field
from typing import Annotated
from .address_verifydef import AddressVerifyDef

from royal_mail_combined import RMBaseModel


class AddressVerifyReqRespdef(RMBaseModel):
    """
    Returns the DPS
    """

    input: AddressVerifyDef | None = Field(default=None, alias='Input')
    dps: Annotated[str, Field(strict=True, max_length=2)] | None = Field(default=None, alias='DPS')
